// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package entv1

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/migrate/entv1/car"
	"entgo.io/ent/entc/integration/migrate/entv1/user"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/runtime/entgen"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetAge sets the "age" field.
func (_c *UserCreate) SetAge(v int32) *UserCreate {
	_c.mutation.SetAge(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *UserCreate) SetDescription(v string) *UserCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UserCreate) SetNillableDescription(v *string) *UserCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *UserCreate) SetNickname(v string) *UserCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *UserCreate) SetAddress(v string) *UserCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *UserCreate) SetNillableAddress(v *string) *UserCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetRenamed sets the "renamed" field.
func (_c *UserCreate) SetRenamed(v string) *UserCreate {
	_c.mutation.SetRenamed(v)
	return _c
}

// SetNillableRenamed sets the "renamed" field if the given value is not nil.
func (_c *UserCreate) SetNillableRenamed(v *string) *UserCreate {
	if v != nil {
		_c.SetRenamed(*v)
	}
	return _c
}

// SetOldToken sets the "old_token" field.
func (_c *UserCreate) SetOldToken(v string) *UserCreate {
	_c.mutation.SetOldToken(v)
	return _c
}

// SetNillableOldToken sets the "old_token" field if the given value is not nil.
func (_c *UserCreate) SetNillableOldToken(v *string) *UserCreate {
	if v != nil {
		_c.SetOldToken(*v)
	}
	return _c
}

// SetBlob sets the "blob" field.
func (_c *UserCreate) SetBlob(v []byte) *UserCreate {
	_c.mutation.SetBlob(v)
	return _c
}

// SetState sets the "state" field.
func (_c *UserCreate) SetState(v user.State) *UserCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *UserCreate) SetNillableState(v *user.State) *UserCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserCreate) SetStatus(v string) *UserCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserCreate) SetNillableStatus(v *string) *UserCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWorkplace sets the "workplace" field.
func (_c *UserCreate) SetWorkplace(v string) *UserCreate {
	_c.mutation.SetWorkplace(v)
	return _c
}

// SetNillableWorkplace sets the "workplace" field if the given value is not nil.
func (_c *UserCreate) SetNillableWorkplace(v *string) *UserCreate {
	if v != nil {
		_c.SetWorkplace(*v)
	}
	return _c
}

// SetDropOptional sets the "drop_optional" field.
func (_c *UserCreate) SetDropOptional(v string) *UserCreate {
	_c.mutation.SetDropOptional(v)
	return _c
}

// SetNillableDropOptional sets the "drop_optional" field if the given value is not nil.
func (_c *UserCreate) SetNillableDropOptional(v *string) *UserCreate {
	if v != nil {
		_c.SetDropOptional(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v int) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParentID sets the "parent" edge to the User entity by ID.
func (_c *UserCreate) SetParentID(id int) *UserCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the User entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableParentID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the User entity.
func (_c *UserCreate) SetParent(v *User) *UserCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the User entity by IDs.
func (_c *UserCreate) AddChildIDs(ids ...int) *UserCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the User entity.
func (_c *UserCreate) AddChildren(v ...*User) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// SetSpouseID sets the "spouse" edge to the User entity by ID.
func (_c *UserCreate) SetSpouseID(id int) *UserCreate {
	_c.mutation.SetSpouseID(id)
	return _c
}

// SetNillableSpouseID sets the "spouse" edge to the User entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableSpouseID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetSpouseID(*id)
	}
	return _c
}

// SetSpouse sets the "spouse" edge to the User entity.
func (_c *UserCreate) SetSpouse(v *User) *UserCreate {
	return _c.SetSpouseID(v.ID)
}

// SetCarID sets the "car" edge to the Car entity by ID.
func (_c *UserCreate) SetCarID(id int) *UserCreate {
	_c.mutation.SetCarID(id)
	return _c
}

// SetNillableCarID sets the "car" edge to the Car entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableCarID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetCarID(*id)
	}
	return _c
}

// SetCar sets the "car" edge to the Car entity.
func (_c *UserCreate) SetCar(v *Car) *UserCreate {
	return _c.SetCarID(v.ID)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	if err := entgen.ApplyDefaults(_c.mutation, userCreateSpec.Fields); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

var userCreateSpec = entgen.CreateSpec[*UserMutation]{
	Fields: []entgen.FieldSpec[*UserMutation]{
		{
			Name: "age",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "age", err: errors.New(`entv1: missing required field "User.age"`)}
				},
			},
			IsSet: func(m *UserMutation) bool {
				_, ok := m.Age()
				return ok
			},
		},
		{
			Name: "name",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "name", err: errors.New(`entv1: missing required field "User.name"`)}
				},
			},
			IsSet: func(m *UserMutation) bool {
				_, ok := m.Name()
				return ok
			},
			Validators: []func(*UserMutation) error{
				func(m *UserMutation) error {
					if v, ok := m.Name(); ok {
						if err := user.NameValidator(v); err != nil {
							return &ValidationError{Name: "name", err: fmt.Errorf(`entv1: validator failed for field "User.name": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "description",
		},
		{
			Name: "nickname",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "nickname", err: errors.New(`entv1: missing required field "User.nickname"`)}
				},
			},
			IsSet: func(m *UserMutation) bool {
				_, ok := m.Nickname()
				return ok
			},
		},
		{
			Name: "address",
		},
		{
			Name: "renamed",
		},
		{
			Name: "old_token",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "old_token", err: errors.New(`entv1: missing required field "User.old_token"`)}
				},
			},
			IsSet: func(m *UserMutation) bool {
				_, ok := m.OldToken()
				return ok
			},
			Default: func(m *UserMutation) error {
				if _, ok := m.OldToken(); !ok {
					v := user.DefaultOldToken()
					m.SetOldToken(v)
				}
				return nil
			},
		},
		{
			Name: "blob",
			Validators: []func(*UserMutation) error{
				func(m *UserMutation) error {
					if v, ok := m.Blob(); ok {
						if err := user.BlobValidator(v); err != nil {
							return &ValidationError{Name: "blob", err: fmt.Errorf(`entv1: validator failed for field "User.blob": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "state",
			Default: func(m *UserMutation) error {
				if _, ok := m.State(); !ok {
					v := user.DefaultState
					m.SetState(v)
				}
				return nil
			},
			Validators: []func(*UserMutation) error{
				func(m *UserMutation) error {
					if v, ok := m.State(); ok {
						if err := user.StateValidator(v); err != nil {
							return &ValidationError{Name: "state", err: fmt.Errorf(`entv1: validator failed for field "User.state": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "status",
		},
		{
			Name: "workplace",
			Validators: []func(*UserMutation) error{
				func(m *UserMutation) error {
					if v, ok := m.Workplace(); ok {
						if err := user.WorkplaceValidator(v); err != nil {
							return &ValidationError{Name: "workplace", err: fmt.Errorf(`entv1: validator failed for field "User.workplace": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "drop_optional",
		},
		{
			Name: "id",
		},
	},
	Edges: []entgen.EdgeSpec[*UserMutation]{},
}

var userCreateDescriptor = entbuilder.CreateDescriptor[config, User, *UserMutation]{
	Table: user.Table,
	NewNode: func(cfg config) *User {
		return &User{config: cfg}
	},
	ID: &entbuilder.IDDescriptor[config, User, *UserMutation]{
		Column:      user.FieldID,
		Type:        field.TypeInt,
		UserDefined: true,
		Value: func(m *UserMutation) (entbuilder.FieldValue, bool, error) {
			if id, ok := m.ID(); ok {
				return entbuilder.FieldValue{Spec: id, Node: id}, true, nil
			}
			return entbuilder.FieldValue{}, false, nil
		},
		AssignNode: func(node *User, fv entbuilder.FieldValue) error {
			node.ID = fv.Node.(int)
			return nil
		},
		AssignGenerated: func(node *User, value driver.Value) error {
			switch v := value.(type) {
			case int:
				node.ID = int(v)
			case int8:
				node.ID = int(v)
			case int16:
				node.ID = int(v)
			case int32:
				node.ID = int(v)
			case int64:
				node.ID = int(v)
			case uint:
				node.ID = int(v)
			case uint8:
				node.ID = int(v)
			case uint16:
				node.ID = int(v)
			case uint32:
				node.ID = int(v)
			case uint64:
				node.ID = int(v)
			default:
				if v, ok := value.(int); ok {
					node.ID = v
					return nil
				}
				return fmt.Errorf("unexpected User.ID type: %T", value)
			}
			return nil
		},
	},

	Fields: []entbuilder.FieldDescriptor[config, User, *UserMutation]{

		entbuilder.SimpleField[config, User, *UserMutation, int32](
			user.FieldAge,
			field.TypeInt32,
			(*UserMutation).Age,
			func(n *User, v int32) { n.Age = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldName,
			field.TypeString,
			(*UserMutation).Name,
			func(n *User, v string) { n.Name = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldDescription,
			field.TypeString,
			(*UserMutation).Description,
			func(n *User, v string) { n.Description = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldNickname,
			field.TypeString,
			(*UserMutation).Nickname,
			func(n *User, v string) { n.Nickname = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldAddress,
			field.TypeString,
			(*UserMutation).Address,
			func(n *User, v string) { n.Address = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldRenamed,
			field.TypeString,
			(*UserMutation).Renamed,
			func(n *User, v string) { n.Renamed = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldOldToken,
			field.TypeString,
			(*UserMutation).OldToken,
			func(n *User, v string) { n.OldToken = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, []byte](
			user.FieldBlob,
			field.TypeBytes,
			(*UserMutation).Blob,
			func(n *User, v []byte) { n.Blob = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, user.State](
			user.FieldState,
			field.TypeEnum,
			(*UserMutation).State,
			func(n *User, v user.State) { n.State = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldStatus,
			field.TypeString,
			(*UserMutation).Status,
			func(n *User, v string) { n.Status = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldWorkplace,
			field.TypeString,
			(*UserMutation).Workplace,
			func(n *User, v string) { n.Workplace = v },
		),

		entbuilder.SimpleField[config, User, *UserMutation, string](
			user.FieldDropOptional,
			field.TypeString,
			(*UserMutation).DropOptional,
			func(n *User, v string) { n.DropOptional = v },
		),
	},
	Edges: []entbuilder.EdgeDescriptor[config, User, *UserMutation]{
		{
			Value: func(cfg config, m *UserMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.ParentIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.M2O,
					Inverse: true,
					Table:   user.ParentTable,
					Columns: []string{user.ParentColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *User, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.user_children = &ids[0]
				return nil
			},
		},

		{
			Value: func(cfg config, m *UserMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.ChildrenIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.O2M,
					Inverse: false,
					Table:   user.ChildrenTable,
					Columns: []string{user.ChildrenColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
		},

		{
			Value: func(cfg config, m *UserMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.SpouseIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.O2O,
					Inverse: false,
					Table:   user.SpouseTable,
					Columns: []string{user.SpouseColumn},
					Bidi:    true,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *User, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.user_spouse = &ids[0]
				return nil
			},
		},

		{
			Value: func(cfg config, m *UserMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.CarIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.O2O,
					Inverse: false,
					Table:   user.CarTable,
					Columns: []string{user.CarColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
		},
	},
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := entgen.CheckCreate(_c.driver.Dialect(), _c.mutation, userCreateSpec); err != nil {
		return nil, err
	}
	_node, _spec, err := entbuilder.BuildCreateSpec(_c.config, _c.mutation, &userCreateDescriptor)
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if err := entbuilder.ApplyGeneratedID(_c.mutation, _spec, _node, &userCreateDescriptor); err != nil {
		return nil, err
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		if err := entgen.ApplyDefaults(_c.builders[i].mutation, userCreateSpec.Fields); err != nil {
			return nil, err
		}
	}
	for i := range _c.builders {
		func(i int, root context.Context) {
			curr := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := entgen.CheckCreate(curr.driver.Dialect(), mutation, userCreateSpec); err != nil {
					return nil, err
				}
				curr.mutation = mutation
				var err error
				nodes[i], specs[i], err = entbuilder.BuildCreateSpec(curr.config, mutation, &userCreateDescriptor)
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
					if err == nil {
						for j := range specs {
							if err = entbuilder.ApplyGeneratedID(_c.builders[j].mutation, specs[j], nodes[j], &userCreateDescriptor); err != nil {
								break
							}
							_c.builders[j].mutation.id = &nodes[j].ID
							_c.builders[j].mutation.done = true
						}
					}
				}
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(curr.hooks) - 1; i >= 0; i-- {
				mut = curr.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
