// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package comment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/ent/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldID, id))
}

// Deprecated: UniqueInt — use where.EQ(FieldUniqueInt, v).
func UniqueInt(v int) predicate.Comment { return where.EQ(FieldUniqueInt, v) }

// Deprecated: UniqueFloat — use where.EQ(FieldUniqueFloat, v).
func UniqueFloat(v float64) predicate.Comment { return where.EQ(FieldUniqueFloat, v) }

// Deprecated: NillableInt — use where.EQ(FieldNillableInt, v).
func NillableInt(v int) predicate.Comment { return where.EQ(FieldNillableInt, v) }

// Deprecated: Client — use where.EQ(FieldClient, v).
func Client(v string) predicate.Comment { return where.EQ(FieldClient, v) }

// Deprecated: UniqueIntEQ — use where.EQ(FieldUniqueInt, v).
func UniqueIntEQ(v int) predicate.Comment { return where.EQ(FieldUniqueInt, v) }

// Deprecated: UniqueIntNEQ — use where.NEQ(FieldUniqueInt, v).
func UniqueIntNEQ(v int) predicate.Comment { return where.NEQ(FieldUniqueInt, v) }

// Deprecated: UniqueIntIn — use where.In(FieldUniqueInt, vs...).
func UniqueIntIn(vs ...int) predicate.Comment { return where.In(FieldUniqueInt, vs...) }

// Deprecated: UniqueIntNotIn — use where.NotIn(FieldUniqueInt, vs...).
func UniqueIntNotIn(vs ...int) predicate.Comment { return where.NotIn(FieldUniqueInt, vs...) }

// Deprecated: UniqueIntGT — use where.GT(FieldUniqueInt, v).
func UniqueIntGT(v int) predicate.Comment { return where.GT(FieldUniqueInt, v) }

// Deprecated: UniqueIntGTE — use where.GTE(FieldUniqueInt, v).
func UniqueIntGTE(v int) predicate.Comment { return where.GTE(FieldUniqueInt, v) }

// Deprecated: UniqueIntLT — use where.LT(FieldUniqueInt, v).
func UniqueIntLT(v int) predicate.Comment { return where.LT(FieldUniqueInt, v) }

// Deprecated: UniqueIntLTE — use where.LTE(FieldUniqueInt, v).
func UniqueIntLTE(v int) predicate.Comment { return where.LTE(FieldUniqueInt, v) }

// Deprecated: UniqueFloatEQ — use where.EQ(FieldUniqueFloat, v).
func UniqueFloatEQ(v float64) predicate.Comment { return where.EQ(FieldUniqueFloat, v) }

// Deprecated: UniqueFloatNEQ — use where.NEQ(FieldUniqueFloat, v).
func UniqueFloatNEQ(v float64) predicate.Comment { return where.NEQ(FieldUniqueFloat, v) }

// Deprecated: UniqueFloatIn — use where.In(FieldUniqueFloat, vs...).
func UniqueFloatIn(vs ...float64) predicate.Comment { return where.In(FieldUniqueFloat, vs...) }

// Deprecated: UniqueFloatNotIn — use where.NotIn(FieldUniqueFloat, vs...).
func UniqueFloatNotIn(vs ...float64) predicate.Comment { return where.NotIn(FieldUniqueFloat, vs...) }

// Deprecated: UniqueFloatGT — use where.GT(FieldUniqueFloat, v).
func UniqueFloatGT(v float64) predicate.Comment { return where.GT(FieldUniqueFloat, v) }

// Deprecated: UniqueFloatGTE — use where.GTE(FieldUniqueFloat, v).
func UniqueFloatGTE(v float64) predicate.Comment { return where.GTE(FieldUniqueFloat, v) }

// Deprecated: UniqueFloatLT — use where.LT(FieldUniqueFloat, v).
func UniqueFloatLT(v float64) predicate.Comment { return where.LT(FieldUniqueFloat, v) }

// Deprecated: UniqueFloatLTE — use where.LTE(FieldUniqueFloat, v).
func UniqueFloatLTE(v float64) predicate.Comment { return where.LTE(FieldUniqueFloat, v) }

// Deprecated: NillableIntEQ — use where.EQ(FieldNillableInt, v).
func NillableIntEQ(v int) predicate.Comment { return where.EQ(FieldNillableInt, v) }

// Deprecated: NillableIntNEQ — use where.NEQ(FieldNillableInt, v).
func NillableIntNEQ(v int) predicate.Comment { return where.NEQ(FieldNillableInt, v) }

// Deprecated: NillableIntIn — use where.In(FieldNillableInt, vs...).
func NillableIntIn(vs ...int) predicate.Comment { return where.In(FieldNillableInt, vs...) }

// Deprecated: NillableIntNotIn — use where.NotIn(FieldNillableInt, vs...).
func NillableIntNotIn(vs ...int) predicate.Comment { return where.NotIn(FieldNillableInt, vs...) }

// Deprecated: NillableIntGT — use where.GT(FieldNillableInt, v).
func NillableIntGT(v int) predicate.Comment { return where.GT(FieldNillableInt, v) }

// Deprecated: NillableIntGTE — use where.GTE(FieldNillableInt, v).
func NillableIntGTE(v int) predicate.Comment { return where.GTE(FieldNillableInt, v) }

// Deprecated: NillableIntLT — use where.LT(FieldNillableInt, v).
func NillableIntLT(v int) predicate.Comment { return where.LT(FieldNillableInt, v) }

// Deprecated: NillableIntLTE — use where.LTE(FieldNillableInt, v).
func NillableIntLTE(v int) predicate.Comment { return where.LTE(FieldNillableInt, v) }

// Deprecated: NillableIntIsNil — use where.IsNull(FieldNillableInt).
func NillableIntIsNil() predicate.Comment { return where.IsNull(FieldNillableInt) }

// Deprecated: NillableIntNotNil — use where.NotNull(FieldNillableInt).
func NillableIntNotNil() predicate.Comment { return where.NotNull(FieldNillableInt) }

// Deprecated: TableEQ — use where.EQ(FieldTable, v).
func TableEQ(v string) predicate.Comment { return where.EQ(FieldTable, v) }

// Deprecated: TableNEQ — use where.NEQ(FieldTable, v).
func TableNEQ(v string) predicate.Comment { return where.NEQ(FieldTable, v) }

// Deprecated: TableIn — use where.In(FieldTable, vs...).
func TableIn(vs ...string) predicate.Comment { return where.In(FieldTable, vs...) }

// Deprecated: TableNotIn — use where.NotIn(FieldTable, vs...).
func TableNotIn(vs ...string) predicate.Comment { return where.NotIn(FieldTable, vs...) }

// Deprecated: TableGT — use where.GT(FieldTable, v).
func TableGT(v string) predicate.Comment { return where.GT(FieldTable, v) }

// Deprecated: TableGTE — use where.GTE(FieldTable, v).
func TableGTE(v string) predicate.Comment { return where.GTE(FieldTable, v) }

// Deprecated: TableLT — use where.LT(FieldTable, v).
func TableLT(v string) predicate.Comment { return where.LT(FieldTable, v) }

// Deprecated: TableLTE — use where.LTE(FieldTable, v).
func TableLTE(v string) predicate.Comment { return where.LTE(FieldTable, v) }

// Deprecated: TableContains — use where.Contains(FieldTable, v).
func TableContains(v string) predicate.Comment { return where.Contains(FieldTable, v) }

// Deprecated: TableHasPrefix — use where.HasPrefix(FieldTable, v).
func TableHasPrefix(v string) predicate.Comment { return where.HasPrefix(FieldTable, v) }

// Deprecated: TableHasSuffix — use where.HasSuffix(FieldTable, v).
func TableHasSuffix(v string) predicate.Comment { return where.HasSuffix(FieldTable, v) }

// Deprecated: TableIsNil — use where.IsNull(FieldTable).
func TableIsNil() predicate.Comment { return where.IsNull(FieldTable) }

// Deprecated: TableNotNil — use where.NotNull(FieldTable).
func TableNotNil() predicate.Comment { return where.NotNull(FieldTable) }

// Deprecated: TableEqualFold — use where.EqualFold(FieldTable, v).
func TableEqualFold(v string) predicate.Comment { return where.EqualFold(FieldTable, v) }

// Deprecated: TableContainsFold — use where.ContainsFold(FieldTable, v).
func TableContainsFold(v string) predicate.Comment { return where.ContainsFold(FieldTable, v) }

// DirIsNil applies the IsNil predicate on the "dir" field.
func DirIsNil() predicate.Comment {
	return predicate.Comment(sql.FieldIsNull(FieldDir))
}

// DirNotNil applies the NotNil predicate on the "dir" field.
func DirNotNil() predicate.Comment {
	return predicate.Comment(sql.FieldNotNull(FieldDir))
}

// Deprecated: ClientEQ — use where.EQ(FieldClient, v).
func ClientEQ(v string) predicate.Comment { return where.EQ(FieldClient, v) }

// Deprecated: ClientNEQ — use where.NEQ(FieldClient, v).
func ClientNEQ(v string) predicate.Comment { return where.NEQ(FieldClient, v) }

// Deprecated: ClientIn — use where.In(FieldClient, vs...).
func ClientIn(vs ...string) predicate.Comment { return where.In(FieldClient, vs...) }

// Deprecated: ClientNotIn — use where.NotIn(FieldClient, vs...).
func ClientNotIn(vs ...string) predicate.Comment { return where.NotIn(FieldClient, vs...) }

// Deprecated: ClientGT — use where.GT(FieldClient, v).
func ClientGT(v string) predicate.Comment { return where.GT(FieldClient, v) }

// Deprecated: ClientGTE — use where.GTE(FieldClient, v).
func ClientGTE(v string) predicate.Comment { return where.GTE(FieldClient, v) }

// Deprecated: ClientLT — use where.LT(FieldClient, v).
func ClientLT(v string) predicate.Comment { return where.LT(FieldClient, v) }

// Deprecated: ClientLTE — use where.LTE(FieldClient, v).
func ClientLTE(v string) predicate.Comment { return where.LTE(FieldClient, v) }

// Deprecated: ClientContains — use where.Contains(FieldClient, v).
func ClientContains(v string) predicate.Comment { return where.Contains(FieldClient, v) }

// Deprecated: ClientHasPrefix — use where.HasPrefix(FieldClient, v).
func ClientHasPrefix(v string) predicate.Comment { return where.HasPrefix(FieldClient, v) }

// Deprecated: ClientHasSuffix — use where.HasSuffix(FieldClient, v).
func ClientHasSuffix(v string) predicate.Comment { return where.HasSuffix(FieldClient, v) }

// Deprecated: ClientIsNil — use where.IsNull(FieldClient).
func ClientIsNil() predicate.Comment { return where.IsNull(FieldClient) }

// Deprecated: ClientNotNil — use where.NotNull(FieldClient).
func ClientNotNil() predicate.Comment { return where.NotNull(FieldClient) }

// Deprecated: ClientEqualFold — use where.EqualFold(FieldClient, v).
func ClientEqualFold(v string) predicate.Comment { return where.EqualFold(FieldClient, v) }

// Deprecated: ClientContainsFold — use where.ContainsFold(FieldClient, v).
func ClientContainsFold(v string) predicate.Comment { return where.ContainsFold(FieldClient, v) }

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.NotPredicates(p))
}
