// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package comment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// F holds typed predicate/order handles for every comparable field of the Comment type.
var F = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// UniqueInt is the handle for the "unique_int" field.
	UniqueInt entfield.Number[int]
	// UniqueFloat is the handle for the "unique_float" field.
	UniqueFloat entfield.Number[float64]
	// NillableInt is the handle for the "nillable_int" field.
	NillableInt entfield.Number[int]
	// Table is the handle for the "table" field.
	Table entfield.String[string]
	// Client is the handle for the "client" field.
	Client entfield.String[string]
}{
	ID:          entfield.NewNumber[int](FieldID),
	UniqueInt:   entfield.NewNumber[int](FieldUniqueInt),
	UniqueFloat: entfield.NewNumber[float64](FieldUniqueFloat),
	NillableInt: entfield.NewNumber[int](FieldNillableInt),
	Table:       entfield.NewString[string](FieldTable),
	Client:      entfield.NewString[string](FieldClient),
}

// E holds typed edge handles for every edge of the Comment type.
var E = struct {
}{}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.NotPredicates(p))
}
