// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/migrate/versioned/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Deprecated: Age — use where.EQ(FieldAge, v).
func Age(v int32) predicate.User { return where.EQ(FieldAge, v) }

// Deprecated: Name — use where.EQ(FieldName, v).
func Name(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: Address — use where.EQ(FieldAddress, v).
func Address(v string) predicate.User { return where.EQ(FieldAddress, v) }

// Deprecated: AgeEQ — use where.EQ(FieldAge, v).
func AgeEQ(v int32) predicate.User { return where.EQ(FieldAge, v) }

// Deprecated: AgeNEQ — use where.NEQ(FieldAge, v).
func AgeNEQ(v int32) predicate.User { return where.NEQ(FieldAge, v) }

// Deprecated: AgeIn — use where.In(FieldAge, vs...).
func AgeIn(vs ...int32) predicate.User { return where.In(FieldAge, vs...) }

// Deprecated: AgeNotIn — use where.NotIn(FieldAge, vs...).
func AgeNotIn(vs ...int32) predicate.User { return where.NotIn(FieldAge, vs...) }

// Deprecated: AgeGT — use where.GT(FieldAge, v).
func AgeGT(v int32) predicate.User { return where.GT(FieldAge, v) }

// Deprecated: AgeGTE — use where.GTE(FieldAge, v).
func AgeGTE(v int32) predicate.User { return where.GTE(FieldAge, v) }

// Deprecated: AgeLT — use where.LT(FieldAge, v).
func AgeLT(v int32) predicate.User { return where.LT(FieldAge, v) }

// Deprecated: AgeLTE — use where.LTE(FieldAge, v).
func AgeLTE(v int32) predicate.User { return where.LTE(FieldAge, v) }

// Deprecated: NameEQ — use where.EQ(FieldName, v).
func NameEQ(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: NameNEQ — use where.NEQ(FieldName, v).
func NameNEQ(v string) predicate.User { return where.NEQ(FieldName, v) }

// Deprecated: NameIn — use where.In(FieldName, vs...).
func NameIn(vs ...string) predicate.User { return where.In(FieldName, vs...) }

// Deprecated: NameNotIn — use where.NotIn(FieldName, vs...).
func NameNotIn(vs ...string) predicate.User { return where.NotIn(FieldName, vs...) }

// Deprecated: NameGT — use where.GT(FieldName, v).
func NameGT(v string) predicate.User { return where.GT(FieldName, v) }

// Deprecated: NameGTE — use where.GTE(FieldName, v).
func NameGTE(v string) predicate.User { return where.GTE(FieldName, v) }

// Deprecated: NameLT — use where.LT(FieldName, v).
func NameLT(v string) predicate.User { return where.LT(FieldName, v) }

// Deprecated: NameLTE — use where.LTE(FieldName, v).
func NameLTE(v string) predicate.User { return where.LTE(FieldName, v) }

// Deprecated: NameContains — use where.Contains(FieldName, v).
func NameContains(v string) predicate.User { return where.Contains(FieldName, v) }

// Deprecated: NameHasPrefix — use where.HasPrefix(FieldName, v).
func NameHasPrefix(v string) predicate.User { return where.HasPrefix(FieldName, v) }

// Deprecated: NameHasSuffix — use where.HasSuffix(FieldName, v).
func NameHasSuffix(v string) predicate.User { return where.HasSuffix(FieldName, v) }

// Deprecated: NameEqualFold — use where.EqualFold(FieldName, v).
func NameEqualFold(v string) predicate.User { return where.EqualFold(FieldName, v) }

// Deprecated: NameContainsFold — use where.ContainsFold(FieldName, v).
func NameContainsFold(v string) predicate.User { return where.ContainsFold(FieldName, v) }

// Deprecated: AddressEQ — use where.EQ(FieldAddress, v).
func AddressEQ(v string) predicate.User { return where.EQ(FieldAddress, v) }

// Deprecated: AddressNEQ — use where.NEQ(FieldAddress, v).
func AddressNEQ(v string) predicate.User { return where.NEQ(FieldAddress, v) }

// Deprecated: AddressIn — use where.In(FieldAddress, vs...).
func AddressIn(vs ...string) predicate.User { return where.In(FieldAddress, vs...) }

// Deprecated: AddressNotIn — use where.NotIn(FieldAddress, vs...).
func AddressNotIn(vs ...string) predicate.User { return where.NotIn(FieldAddress, vs...) }

// Deprecated: AddressGT — use where.GT(FieldAddress, v).
func AddressGT(v string) predicate.User { return where.GT(FieldAddress, v) }

// Deprecated: AddressGTE — use where.GTE(FieldAddress, v).
func AddressGTE(v string) predicate.User { return where.GTE(FieldAddress, v) }

// Deprecated: AddressLT — use where.LT(FieldAddress, v).
func AddressLT(v string) predicate.User { return where.LT(FieldAddress, v) }

// Deprecated: AddressLTE — use where.LTE(FieldAddress, v).
func AddressLTE(v string) predicate.User { return where.LTE(FieldAddress, v) }

// Deprecated: AddressContains — use where.Contains(FieldAddress, v).
func AddressContains(v string) predicate.User { return where.Contains(FieldAddress, v) }

// Deprecated: AddressHasPrefix — use where.HasPrefix(FieldAddress, v).
func AddressHasPrefix(v string) predicate.User { return where.HasPrefix(FieldAddress, v) }

// Deprecated: AddressHasSuffix — use where.HasSuffix(FieldAddress, v).
func AddressHasSuffix(v string) predicate.User { return where.HasSuffix(FieldAddress, v) }

// Deprecated: AddressIsNil — use where.IsNull(FieldAddress).
func AddressIsNil() predicate.User { return where.IsNull(FieldAddress) }

// Deprecated: AddressNotNil — use where.NotNull(FieldAddress).
func AddressNotNil() predicate.User { return where.NotNull(FieldAddress) }

// Deprecated: AddressEqualFold — use where.EqualFold(FieldAddress, v).
func AddressEqualFold(v string) predicate.User { return where.EqualFold(FieldAddress, v) }

// Deprecated: AddressContainsFold — use where.ContainsFold(FieldAddress, v).
func AddressContainsFold(v string) predicate.User { return where.ContainsFold(FieldAddress, v) }

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
