// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/multischema/ent/internal"
	"entgo.io/ent/entc/integration/multischema/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// F holds typed predicate/order handles for every comparable field of the User type.
var F = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// Name is the handle for the "name" field.
	Name entfield.String[string]
}{
	ID:   entfield.NewNumber[int](FieldID),
	Name: entfield.NewString[string](FieldName),
}

// E holds typed edge handles for every edge of the User type.
var E = struct {
	// Pets is the handle for the "pets" edge.
	Pets entfield.Edge[predicate.Pet]
	// Groups is the handle for the "groups" edge.
	Groups entfield.Edge[predicate.Group]
	// Friends is the handle for the "friends" edge.
	Friends entfield.Edge[predicate.User]
	// Parents is the handle for the "parents" edge.
	Parents entfield.Edge[predicate.User]
	// Children is the handle for the "children" edge.
	Children entfield.Edge[predicate.User]
	// Friendships is the handle for the "friendships" edge.
	Friendships entfield.Edge[predicate.Friendship]
	// ParentHood is the handle for the "parent_hood" edge.
	ParentHood entfield.Edge[predicate.Parent]
}{
	Pets: entfield.NewEdgeSteps[predicate.Pet](newPetsStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.Pet
			step.Edge.Schema = schemaConfig.Pet
		},
	}),
	Groups: entfield.NewEdgeSteps[predicate.Group](newGroupsStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.Group
			step.Edge.Schema = schemaConfig.GroupUsers
		},
	}),
	Friends: entfield.NewEdgeSteps[predicate.User](newFriendsStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.User
			step.Edge.Schema = schemaConfig.Friendship
		},
	}),
	Parents: entfield.NewEdgeSteps[predicate.User](newParentsStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.User
			step.Edge.Schema = schemaConfig.UserChildren
		},
	}),
	Children: entfield.NewEdgeSteps[predicate.User](newChildrenStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.User
			step.Edge.Schema = schemaConfig.Parent
		},
	}),
	Friendships: entfield.NewEdgeSteps[predicate.Friendship](newFriendshipsStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.Friendship
			step.Edge.Schema = schemaConfig.Friendship
		},
	}),
	ParentHood: entfield.NewEdgeSteps[predicate.Parent](newParentHoodStep, []func(*sql.Selector, *sqlgraph.Step){
		func(s *sql.Selector, step *sqlgraph.Step) {
			schemaConfig := internal.SchemaConfigFromContext(s.Context())
			step.To.Schema = schemaConfig.Parent
			step.Edge.Schema = schemaConfig.Parent
		},
	}),
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
