// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"

	"entgo.io/ent/entc/integration/edgeschema/ent/file"
	"entgo.io/ent/entc/integration/edgeschema/ent/process"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	FileClient     = file.FileClient
	FileQuery      = file.FileQuery
	FileMutation   = file.FileMutation
	FileCreate     = file.FileCreate
	FileCreateBulk = file.FileCreateBulk
	FileUpdate     = file.FileUpdate
	FileUpdateOne  = file.FileUpdateOne
	FileDelete     = file.FileDelete
	FileDeleteOne  = file.FileDeleteOne
	FileGroupBy    = file.FileGroupBy
	FileSelect     = file.FileSelect
	FileFilter     = file.FileFilter
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewFileClient            = file.NewFileClient
	NewFileFilterForMutation = file.NewFileFilterForMutation
)

// WithFileProcesses eager-loads the "processes" edge on a FileQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithFileProcesses(q *FileQuery, opts ...func(*ProcessQuery)) *FileQuery {
	sub := NewProcessClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("processes", func(ctx context.Context, parents []*File) error {
		return loadFileProcesses(ctx, sub, parents)
	})
}

// QueryFileProcesses returns a ProcessQuery for the "processes" edge of a given File.
func QueryFileProcesses(c *FileClient, _m *File) *ProcessQuery {
	query := NewProcessClient(c.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(file.Table, file.FieldID, id),
			sqlgraph.To(process.Table, process.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, file.ProcessesTable, file.ProcessesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)

		return fromV, nil
	}
	return query
}

// loadFileProcesses performs the eager-load for the "processes" edge. Body mirrors
// the pre-PR6 *FileQuery.loadProcesses method, hoisted to root
// so it can reference cross-package types directly.
func loadFileProcesses(ctx context.Context, query *ProcessQuery, nodes []*File) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*File)
	nids := make(map[int]map[*File]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		node.Edges.Processes = []*Process{}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(file.ProcessesTable)
		s.Join(joinT).On(s.C(process.FieldID), joinT.C(file.ProcessesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(file.ProcessesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(file.ProcessesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.PrepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.Fetch(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*File]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Process](ctx, query, qr, query.QueryState.Inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "processes" node returned %v`, n.ID)
		}
		for kn := range parents {
			kn.Edges.Processes = append(kn.Edges.Processes, n)
		}
	}
	return nil
}
