// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgeschema/ent/group"
	"entgo.io/ent/entc/integration/edgeschema/ent/grouptag"
	"entgo.io/ent/entc/integration/edgeschema/ent/tag"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/runtime/entgen"
	"entgo.io/ent/schema/field"
)

// GroupTagCreate is the builder for creating a GroupTag entity.
type GroupTagCreate struct {
	config
	mutation *GroupTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTagID sets the "tag_id" field.
func (_c *GroupTagCreate) SetTagID(v int) *GroupTagCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupTagCreate) SetGroupID(v int) *GroupTagCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetTag sets the "tag" edge to the Tag entity.
func (_c *GroupTagCreate) SetTag(v *Tag) *GroupTagCreate {
	return _c.SetTagID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupTagCreate) SetGroup(v *Group) *GroupTagCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupTagMutation object of the builder.
func (_c *GroupTagCreate) Mutation() *GroupTagMutation {
	return _c.mutation
}

// Save creates the GroupTag in the database.
func (_c *GroupTagCreate) Save(ctx context.Context) (*GroupTag, error) {
	if err := entgen.ApplyDefaults(_c.mutation, grouptagCreateSpec.Fields); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupTagCreate) SaveX(ctx context.Context) *GroupTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

var grouptagCreateSpec = entgen.CreateSpec[*GroupTagMutation]{
	Fields: []entgen.FieldSpec[*GroupTagMutation]{
		{
			Name: "tag_id",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "GroupTag.tag_id"`)}
				},
			},
			IsSet: func(m *GroupTagMutation) bool {
				_, ok := m.TagID()
				return ok
			},
		},
		{
			Name: "group_id",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupTag.group_id"`)}
				},
			},
			IsSet: func(m *GroupTagMutation) bool {
				_, ok := m.GroupID()
				return ok
			},
		},
	},
	Edges: []entgen.EdgeSpec[*GroupTagMutation]{
		{
			Name: "tag",
			Requirement: entgen.EdgeRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "GroupTag.tag"`)}
				},
			},
			Count: func(m *GroupTagMutation) int {
				return len(m.TagIDs())
			},
		},
		{
			Name: "group",
			Requirement: entgen.EdgeRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupTag.group"`)}
				},
			},
			Count: func(m *GroupTagMutation) int {
				return len(m.GroupIDs())
			},
		},
	},
}

var grouptagCreateDescriptor = entbuilder.CreateDescriptor[config, GroupTag, *GroupTagMutation]{
	Table: grouptag.Table,
	NewNode: func(cfg config) *GroupTag {
		return &GroupTag{config: cfg}
	},
	ID: &entbuilder.IDDescriptor[config, GroupTag, *GroupTagMutation]{
		Column:      grouptag.FieldID,
		Type:        field.TypeInt,
		UserDefined: false,
		AssignGenerated: func(node *GroupTag, value driver.Value) error {
			switch v := value.(type) {
			case int:
				node.ID = int(v)
			case int8:
				node.ID = int(v)
			case int16:
				node.ID = int(v)
			case int32:
				node.ID = int(v)
			case int64:
				node.ID = int(v)
			case uint:
				node.ID = int(v)
			case uint8:
				node.ID = int(v)
			case uint16:
				node.ID = int(v)
			case uint32:
				node.ID = int(v)
			case uint64:
				node.ID = int(v)
			default:
				if v, ok := value.(int); ok {
					node.ID = v
					return nil
				}
				return fmt.Errorf("unexpected GroupTag.ID type: %T", value)
			}
			return nil
		},
	},

	Edges: []entbuilder.EdgeDescriptor[config, GroupTag, *GroupTagMutation]{
		{
			Value: func(cfg config, m *GroupTagMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.TagIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.M2O,
					Inverse: false,
					Table:   grouptag.TagTable,
					Columns: []string{grouptag.TagColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *GroupTag, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.TagID = ids[0]
				return nil
			},
		},

		{
			Value: func(cfg config, m *GroupTagMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.GroupIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.M2O,
					Inverse: false,
					Table:   grouptag.GroupTable,
					Columns: []string{grouptag.GroupColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *GroupTag, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.GroupID = ids[0]
				return nil
			},
		},
	},
}

func (_c *GroupTagCreate) sqlSave(ctx context.Context) (*GroupTag, error) {
	if err := entgen.CheckCreate(_c.driver.Dialect(), _c.mutation, grouptagCreateSpec); err != nil {
		return nil, err
	}
	_node, _spec, err := entbuilder.BuildCreateSpec(_c.config, _c.mutation, &grouptagCreateDescriptor)
	if err != nil {
		return nil, err
	}
	_spec.OnConflict = _c.conflict
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if err := entbuilder.ApplyGeneratedID(_c.mutation, _spec, _node, &grouptagCreateDescriptor); err != nil {
		return nil, err
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupTag.Create().
//		SetTagID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupTagUpsert) {
//			SetTagID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupTagCreate) OnConflict(opts ...sql.ConflictOption) *GroupTagUpsertOne {
	_c.conflict = opts
	return &GroupTagUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupTagCreate) OnConflictColumns(columns ...string) *GroupTagUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupTagUpsertOne{
		create: _c,
	}
}

type (
	// GroupTagUpsertOne is the builder for "upsert"-ing
	//  one GroupTag node.
	GroupTagUpsertOne struct {
		create *GroupTagCreate
	}

	// GroupTagUpsert is the "OnConflict" setter.
	GroupTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetTagID sets the "tag_id" field.
func (u *GroupTagUpsert) SetTagID(v int) *GroupTagUpsert {
	u.Set(grouptag.FieldTagID, v)
	return u
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupTagUpsert) UpdateTagID() *GroupTagUpsert {
	u.SetExcluded(grouptag.FieldTagID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupTagUpsert) SetGroupID(v int) *GroupTagUpsert {
	u.Set(grouptag.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupTagUpsert) UpdateGroupID() *GroupTagUpsert {
	u.SetExcluded(grouptag.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupTagUpsertOne) UpdateNewValues() *GroupTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupTagUpsertOne) Ignore() *GroupTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupTagUpsertOne) DoNothing() *GroupTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupTagCreate.OnConflict
// documentation for more info.
func (u *GroupTagUpsertOne) Update(set func(*GroupTagUpsert)) *GroupTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetTagID sets the "tag_id" field.
func (u *GroupTagUpsertOne) SetTagID(v int) *GroupTagUpsertOne {
	return u.Update(func(s *GroupTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupTagUpsertOne) UpdateTagID() *GroupTagUpsertOne {
	return u.Update(func(s *GroupTagUpsert) {
		s.UpdateTagID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupTagUpsertOne) SetGroupID(v int) *GroupTagUpsertOne {
	return u.Update(func(s *GroupTagUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupTagUpsertOne) UpdateGroupID() *GroupTagUpsertOne {
	return u.Update(func(s *GroupTagUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *GroupTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupTagUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupTagUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupTagCreateBulk is the builder for creating many GroupTag entities in bulk.
type GroupTagCreateBulk struct {
	config
	err      error
	builders []*GroupTagCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupTag entities in the database.
func (_c *GroupTagCreateBulk) Save(ctx context.Context) ([]*GroupTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		if err := entgen.ApplyDefaults(_c.builders[i].mutation, grouptagCreateSpec.Fields); err != nil {
			return nil, err
		}
	}
	for i := range _c.builders {
		func(i int, root context.Context) {
			curr := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := entgen.CheckCreate(curr.driver.Dialect(), mutation, grouptagCreateSpec); err != nil {
					return nil, err
				}
				curr.mutation = mutation
				var err error
				nodes[i], specs[i], err = entbuilder.BuildCreateSpec(curr.config, mutation, &grouptagCreateDescriptor)
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
					if err == nil {
						for j := range specs {
							if err = entbuilder.ApplyGeneratedID(_c.builders[j].mutation, specs[j], nodes[j], &grouptagCreateDescriptor); err != nil {
								break
							}
							_c.builders[j].mutation.id = &nodes[j].ID
							_c.builders[j].mutation.done = true
						}
					}
				}
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(curr.hooks) - 1; i >= 0; i-- {
				mut = curr.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupTagCreateBulk) SaveX(ctx context.Context) []*GroupTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupTagUpsert) {
//			SetTagID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupTagUpsertBulk {
	_c.conflict = opts
	return &GroupTagUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupTagCreateBulk) OnConflictColumns(columns ...string) *GroupTagUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupTagUpsertBulk{
		create: _c,
	}
}

// GroupTagUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupTag nodes.
type GroupTagUpsertBulk struct {
	create *GroupTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupTagUpsertBulk) UpdateNewValues() *GroupTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupTagUpsertBulk) Ignore() *GroupTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupTagUpsertBulk) DoNothing() *GroupTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupTagCreateBulk.OnConflict
// documentation for more info.
func (u *GroupTagUpsertBulk) Update(set func(*GroupTagUpsert)) *GroupTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetTagID sets the "tag_id" field.
func (u *GroupTagUpsertBulk) SetTagID(v int) *GroupTagUpsertBulk {
	return u.Update(func(s *GroupTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupTagUpsertBulk) UpdateTagID() *GroupTagUpsertBulk {
	return u.Update(func(s *GroupTagUpsert) {
		s.UpdateTagID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupTagUpsertBulk) SetGroupID(v int) *GroupTagUpsertBulk {
	return u.Update(func(s *GroupTagUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupTagUpsertBulk) UpdateGroupID() *GroupTagUpsertBulk {
	return u.Update(func(s *GroupTagUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *GroupTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
