// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/edgeschema/ent/grouptag"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
)

// AddPredicate implements the predicateAdder interface.
func (_q *GroupTagQuery) AddPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the GroupTagQuery builder.
func (_q *GroupTagQuery) Filter() *GroupTagFilter {
	return &GroupTagFilter{Config: _q.Config, predicateAdder: _q}
}

// NewGroupTagFilterForMutation creates a new GroupTagFilter for the given mutation.
func NewGroupTagFilterForMutation(m *GroupTagMutation) *GroupTagFilter {
	return &GroupTagFilter{Config: m.Config, predicateAdder: m}
}

// GroupTagFilter provides a generic filtering capability at runtime for GroupTagQuery.
type GroupTagFilter struct {
	predicateAdder
	Config
}

// Where applies the entql predicate on the query filter.
func (f *GroupTagFilter) Where(p entql.P) {
	f.AddPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP("GroupTag", p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *GroupTagFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(grouptag.FieldID))
}

// WhereTagID applies the entql int predicate on the tag_id field.
func (f *GroupTagFilter) WhereTagID(p entql.IntP) {
	f.Where(p.Field(grouptag.FieldTagID))
}

// WhereGroupID applies the entql int predicate on the group_id field.
func (f *GroupTagFilter) WhereGroupID(p entql.IntP) {
	f.Where(p.Field(grouptag.FieldGroupID))
}

// WhereHasTag applies a predicate to check if query has an edge tag.
func (f *GroupTagFilter) WhereHasTag() {
	f.Where(entql.HasEdge("tag"))
}

// WhereHasTagWith applies a predicate to check if query has an edge tag with a given conditions (other predicates).
func (f *GroupTagFilter) WhereHasTagWith(preds ...predicate.Tag) {
	f.Where(entql.HasEdgeWith("tag", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasGroup applies a predicate to check if query has an edge group.
func (f *GroupTagFilter) WhereHasGroup() {
	f.Where(entql.HasEdge("group"))
}

// WhereHasGroupWith applies a predicate to check if query has an edge group with a given conditions (other predicates).
func (f *GroupTagFilter) WhereHasGroupWith(preds ...predicate.Group) {
	f.Where(entql.HasEdgeWith("group", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
