// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgeschema/ent/group"
	"entgo.io/ent/entc/integration/edgeschema/ent/grouptag"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"
	"entgo.io/ent/entc/integration/edgeschema/ent/tag"
	"entgo.io/ent/entc/integration/edgeschema/ent/tweet"
	"entgo.io/ent/entc/integration/edgeschema/ent/tweettag"
)

// TagClient is a client for the Tag schema.
type TagClient struct {
	Config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c Config) *TagClient {
	return &TagClient{Config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.Config.Hooks.Tag = append(c.Config.Hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.Config.Inters.Tag = append(c.Config.Inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *tag.TagCreate {
	mutation := NewTagMutation(c.Config, OpCreate)
	return tag.NewTagCreate(c.Config, c.Hooks(), mutation)
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*tag.TagCreate) *tag.TagCreateBulk {
	return tag.NewTagCreateBulk(c.Config, builders)
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*tag.TagCreate, int)) *tag.TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return tag.NewTagCreateBulkErr(fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice))
	}
	builders := make([]*tag.TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return tag.NewTagCreateBulk(c.Config, builders)
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *tag.TagUpdate {
	mutation := NewTagMutation(c.Config, OpUpdate, WithTagIDsFunc(func(ctx context.Context, ps ...predicate.Tag) ([]int, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return tag.NewTagUpdate(c.Config, c.Hooks(), mutation)
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *tag.TagUpdateOne {
	mutation := NewTagMutation(c.Config, OpUpdateOne, WithTag(_m))
	return tag.NewTagUpdateOne(c.Config, c.Hooks(), mutation)
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int) *tag.TagUpdateOne {
	mutation := NewTagMutation(c.Config, OpUpdateOne, WithTagID(id, c.Get))
	return tag.NewTagUpdateOne(c.Config, c.Hooks(), mutation)
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *tag.TagDelete {
	mutation := NewTagMutation(c.Config, OpDelete, WithTagIDsFunc(func(ctx context.Context, ps ...predicate.Tag) ([]int, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return tag.NewTagDelete(c.Config, c.Hooks(), mutation)
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *tag.TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id int) *tag.TagDeleteOne {
	mutation := NewTagMutation(c.Config, OpDeleteOne, WithTagID(id, nil))
	mutation.Where(tag.ID(id))
	return tag.NewTagDeleteOne(tag.NewTagDelete(c.Config, c.Hooks(), mutation))
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		Config: c.Config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTweets queries the tweets edge of a Tag.
func (c *TagClient) QueryTweets(_m *Tag) *TweetQuery {
	query := (&TweetClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(tweet.Table, tweet.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, tag.TweetsTable, tag.TweetsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGroups queries the groups edge of a Tag.
func (c *TagClient) QueryGroups(_m *Tag) *GroupQuery {
	query := (&GroupClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, tag.GroupsTable, tag.GroupsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTweetTags queries the tweet_tags edge of a Tag.
func (c *TagClient) QueryTweetTags(_m *Tag) *TweetTagQuery {
	query := (&TweetTagClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(tweettag.Table, tweettag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, tag.TweetTagsTable, tag.TweetTagsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGroupTags queries the group_tags edge of a Tag.
func (c *TagClient) QueryGroupTags(_m *Tag) *GroupTagQuery {
	query := (&GroupTagClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(grouptag.Table, grouptag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, tag.GroupTagsTable, tag.GroupTagsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.Config.Hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.Config.Inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return tag.NewTagCreate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdate:
		return tag.NewTagUpdate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdateOne:
		return tag.NewTagUpdateOne(c.Config, c.Hooks(), m).Save(ctx)
	case OpDelete, OpDeleteOne:
		return tag.NewTagDelete(c.Config, c.Hooks(), m).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}
