// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package relationshipinfo

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// Field holds typed predicate/order handles for every comparable field of the RelationshipInfo type.
var Field = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// Text is the handle for the "text" field.
	Text entfield.String[string]
}{
	ID:   entfield.NewNumber[int](FieldID, "id"),
	Text: entfield.NewString[string](FieldText, "text"),
}

// Edge holds typed edge handles for every edge of the RelationshipInfo type.
var Edge = struct {
}{}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelationshipInfo) predicate.RelationshipInfo {
	return predicate.RelationshipInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelationshipInfo) predicate.RelationshipInfo {
	return predicate.RelationshipInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelationshipInfo) predicate.RelationshipInfo {
	return predicate.RelationshipInfo(sql.NotPredicates(p))
}
