// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/examples/migration/ent/predicate"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	Config
	hooks    []Hook
	mutation *UserMutation
}

// NewUserUpdate returns a new UserUpdate initialized with the given config, hooks, and mutation.
func NewUserUpdate(c Config, hooks []Hook, mutation *UserMutation) *UserUpdate {
	return &UserUpdate{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.WhereP(ps...)
	return _u
}

// SetAge sets the "age" field.
func (_u *UserUpdate) SetAge(v float64) *UserUpdate {
	_ = _u.mutation.ResetField("age")
	_ = _u.mutation.SetField("age", v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAge(v *float64) *UserUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdate) AddAge(v float64) *UserUpdate {
	_ = _u.mutation.AddField("age", v)
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdate) SetFirstName(v string) *UserUpdate {
	_ = _u.mutation.SetField("first_name", v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFirstName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdate) SetLastName(v string) *UserUpdate {
	_ = _u.mutation.SetField("last_name", v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastName(v *string) *UserUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdate) SetTags(v []string) *UserUpdate {
	_ = _u.mutation.SetField("tags", v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdate) AppendTags(v []string) *UserUpdate {
	_ = _u.mutation.AppendField("tags", v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdate) ClearTags() *UserUpdate {
	_ = _u.mutation.ClearField("tags")
	return _u
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (_u *UserUpdate) AddCardIDs(ids ...int) *UserUpdate {
	_ = _u.mutation.AddEdgeIDs("cards", entbuilder.ToAny(ids)...)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearCards clears all "cards" edges to the Card entity.
func (_u *UserUpdate) ClearCards() *UserUpdate {
	_ = _u.mutation.ClearEdge("cards")
	return _u
}

// RemoveCardIDs removes the "cards" edge to Card entities by IDs.
func (_u *UserUpdate) RemoveCardIDs(ids ...int) *UserUpdate {
	_ = _u.mutation.RemoveEdgeIDs("cards", entbuilder.ToAny(ids)...)
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return entbuilder.RunUpdate(ctx, &entbuilder.UpdateState[*UserMutation]{Hooks: _u.hooks, Mutation: _u.mutation}, _u.sqlSave)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := entbuilder.GetField[float64](_u.mutation, "age"); ok {
		_spec.SetField(FieldAge, field.TypeFloat64, value)
	}
	if added, ok := _u.mutation.AddedField("age"); ok {
		value := added.(float64)
		_spec.AddField(FieldAge, field.TypeFloat64, value)
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "first_name"); ok {
		_spec.SetField(FieldFirstName, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "last_name"); ok {
		_spec.SetField(FieldLastName, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[[]string](_u.mutation, "tags"); ok {
		_spec.SetField(FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedField("tags"); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, FieldTags, value.([]string))
		})
	}
	if _u.mutation.FieldCleared("tags") {
		_spec.ClearField(FieldTags, field.TypeJSON)
	}
	if _u.mutation.EdgeCleared("cards") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEdgeIDs("cards"); len(nodes) > 0 && !_u.mutation.EdgeCleared("cards") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("cards"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return 0, err
	}
	_u.mutation.SetDone()
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	Config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// NewUserUpdateOne returns a new UserUpdateOne initialized with the given config, hooks, and mutation.
func NewUserUpdateOne(c Config, hooks []Hook, mutation *UserMutation) *UserUpdateOne {
	return &UserUpdateOne{Config: c, hooks: hooks, mutation: mutation}
}

// SetAge sets the "age" field.
func (_u *UserUpdateOne) SetAge(v float64) *UserUpdateOne {
	_ = _u.mutation.ResetField("age")
	_ = _u.mutation.SetField("age", v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAge(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdateOne) AddAge(v float64) *UserUpdateOne {
	_ = _u.mutation.AddField("age", v)
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *UserUpdateOne) SetFirstName(v string) *UserUpdateOne {
	_ = _u.mutation.SetField("first_name", v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFirstName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdateOne) SetLastName(v string) *UserUpdateOne {
	_ = _u.mutation.SetField("last_name", v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdateOne) SetTags(v []string) *UserUpdateOne {
	_ = _u.mutation.SetField("tags", v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *UserUpdateOne) AppendTags(v []string) *UserUpdateOne {
	_ = _u.mutation.AppendField("tags", v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdateOne) ClearTags() *UserUpdateOne {
	_ = _u.mutation.ClearField("tags")
	return _u
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (_u *UserUpdateOne) AddCardIDs(ids ...int) *UserUpdateOne {
	_ = _u.mutation.AddEdgeIDs("cards", entbuilder.ToAny(ids)...)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearCards clears all "cards" edges to the Card entity.
func (_u *UserUpdateOne) ClearCards() *UserUpdateOne {
	_ = _u.mutation.ClearEdge("cards")
	return _u
}

// RemoveCardIDs removes the "cards" edge to Card entities by IDs.
func (_u *UserUpdateOne) RemoveCardIDs(ids ...int) *UserUpdateOne {
	_ = _u.mutation.RemoveEdgeIDs("cards", entbuilder.ToAny(ids)...)
	return _u
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.WhereP(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return entbuilder.RunUpdateOne[User](ctx, &entbuilder.UpdateState[*UserMutation]{Hooks: _u.hooks, Mutation: _u.mutation}, _u.sqlSave)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", Err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, FieldID)
		for _, f := range fields {
			if !ValidColumn(f) {
				return nil, &ValidationError{Name: f, Err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := entbuilder.GetField[float64](_u.mutation, "age"); ok {
		_spec.SetField(FieldAge, field.TypeFloat64, value)
	}
	if added, ok := _u.mutation.AddedField("age"); ok {
		value := added.(float64)
		_spec.AddField(FieldAge, field.TypeFloat64, value)
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "first_name"); ok {
		_spec.SetField(FieldFirstName, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "last_name"); ok {
		_spec.SetField(FieldLastName, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[[]string](_u.mutation, "tags"); ok {
		_spec.SetField(FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedField("tags"); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, FieldTags, value.([]string))
		})
	}
	if _u.mutation.FieldCleared("tags") {
		_spec.ClearField(FieldTags, field.TypeJSON)
	}
	if _u.mutation.EdgeCleared("cards") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEdgeIDs("cards"); len(nodes) > 0 && !_u.mutation.EdgeCleared("cards") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("cards"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   CardsTable,
			Columns: []string{CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{Config: _u.Config}
	_spec.Assign = _node.AssignValues
	_spec.ScanValues = _node.ScanValues
	if err = sqlgraph.UpdateNode(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return nil, err
	}
	_u.mutation.SetDone()
	return _node, nil
}
