// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package account

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent/entc/integration/customid/ent/predicate"
	"entgo.io/ent/entc/integration/customid/sid"
	"entgo.io/ent/runtime/entbuilder"
)

// AccountClient is a client for the Account schema.
type AccountClient struct {
	Config
}

// NewAccountClient returns a client for the Account from the given config.
func NewAccountClient(c Config) *AccountClient {
	return &AccountClient{Config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `Hooks(f(g(h())))`.
func (c *AccountClient) Use(hooks ...Hook) {
	c.Config.Hooks.Account = append(c.Config.Hooks.Account, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `Intercept(f(g(h())))`.
func (c *AccountClient) Intercept(interceptors ...Interceptor) {
	c.Config.Inters.Account = append(c.Config.Inters.Account, interceptors...)
}

// Create returns a builder for creating a Account entity.
func (c *AccountClient) Create() *AccountCreate {
	mutation := NewAccountMutation(c.Config, OpCreate)
	return NewAccountCreate(c.Config, c.Hooks(), mutation)
}

// CreateBulk returns a builder for creating a bulk of Account entities.
func (c *AccountClient) CreateBulk(builders ...*AccountCreate) *AccountCreateBulk {
	return NewAccountCreateBulk(c.Config, builders)
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AccountClient) MapCreateBulk(slice any, setFunc func(*AccountCreate, int)) *AccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return NewAccountCreateBulkErr(fmt.Errorf("calling to AccountClient.MapCreateBulk with wrong type %T, need slice", slice))
	}
	builders := make([]*AccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return NewAccountCreateBulk(c.Config, builders)
}

// Update returns an update builder for Account.
func (c *AccountClient) Update() *AccountUpdate {
	mutation := NewAccountMutation(c.Config, OpUpdate, WithAccountIDsFunc(func(ctx context.Context, ps ...predicate.Account) ([]sid.ID, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return NewAccountUpdate(c.Config, c.Hooks(), mutation)
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountClient) UpdateOne(_m *Account) *AccountUpdateOne {
	mutation := NewAccountMutation(c.Config, OpUpdateOne, WithAccount(_m))
	return NewAccountUpdateOne(c.Config, c.Hooks(), mutation)
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountClient) UpdateOneID(id sid.ID) *AccountUpdateOne {
	mutation := NewAccountMutation(c.Config, OpUpdateOne, WithAccountID(id, c.Get))
	return NewAccountUpdateOne(c.Config, c.Hooks(), mutation)
}

// Delete returns a delete builder for Account.
func (c *AccountClient) Delete() *AccountDelete {
	mutation := NewAccountMutation(c.Config, OpDelete, WithAccountIDsFunc(func(ctx context.Context, ps ...predicate.Account) ([]sid.ID, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return NewAccountDelete(c.Config, c.Hooks(), mutation)
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AccountClient) DeleteOne(_m *Account) *AccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AccountClient) DeleteOneID(id sid.ID) *AccountDeleteOne {
	mutation := NewAccountMutation(c.Config, OpDeleteOne, WithAccountID(id, nil))
	mutation.WhereP(ID(id))
	return NewAccountDeleteOne(NewAccountDelete(c.Config, c.Hooks(), mutation))
}

// Query returns a query builder for Account.
func (c *AccountClient) Query() *AccountQuery {
	return &AccountQuery{
		Config: c.Config,
		QueryState: entbuilder.QueryState[predicate.Account]{
			Ctx:    &QueryContext{Type: TypeAccount},
			Inters: c.Interceptors(),
		},
	}
}

// Get returns a Account entity by its id.
func (c *AccountClient) Get(ctx context.Context, id sid.ID) (*Account, error) {
	return c.Query().Where(ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountClient) GetX(ctx context.Context, id sid.ID) *Account {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AccountClient) Hooks() []Hook {
	return c.Config.Hooks.Account
}

// Interceptors returns the client interceptors.
func (c *AccountClient) Interceptors() []Interceptor {
	return c.Config.Inters.Account
}

// Mutate dispatches a mutation to the appropriate builder. Exported so
// the root Client.Mutate switch can dispatch into the sub-package across
// the package boundary (PR 6).
func (c *AccountClient) Mutate(ctx context.Context, m *AccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return NewAccountCreate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdate:
		return NewAccountUpdate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdateOne:
		return NewAccountUpdateOne(c.Config, c.Hooks(), m).Save(ctx)
	case OpDelete, OpDeleteOne:
		return NewAccountDelete(c.Config, c.Hooks(), m).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Account mutation op: %q", m.Op())
	}
}
