// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package pc

import (
	"context"
	"errors"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"entgo.io/ent/entc/integration/gremlin/ent/predicate"
	"entgo.io/ent/runtime/entbuilder"
)

// PCUpdate is the builder for updating PC entities.
type PCUpdate struct {
	Config
	hooks    []Hook
	mutation *PCMutation
}

// NewPCUpdate returns a new PCUpdate initialized with the given config, hooks, and mutation.
func NewPCUpdate(c Config, hooks []Hook, mutation *PCMutation) *PCUpdate {
	return &PCUpdate{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the PCUpdate builder.
func (_u *PCUpdate) Where(ps ...predicate.PC) *PCUpdate { _u.mutation.Where(ps...); return _u }

// Mutation returns the PCMutation object of the builder.
func (_u *PCUpdate) Mutation() *PCMutation { return _u.mutation }

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PCUpdate) Save(ctx context.Context) (int, error) {
	return WithHooks(ctx, _u.gremlinSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PCUpdate) SaveX(ctx context.Context) int { return entbuilder.Must(_u.Save(ctx)) }

// Exec executes the query.
func (_u *PCUpdate) Exec(ctx context.Context) error { _, err := _u.Save(ctx); return err }

// ExecX is like Exec, but panics if an error occurs.
func (_u *PCUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PCUpdate) gremlinSave(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := _u.gremlin().Query()
	if err := _u.Drv.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	if err, ok := isConstantError(res); ok {
		return 0, err
	}
	_u.mutation.SetDone()
	return res.ReadInt()
}

func (_u *PCUpdate) gremlin() *dsl.Traversal {
	v := g.V().HasLabel(Label)
	for _, p := range _u.mutation.MutationPredicates() {
		p(v)
	}
	var (
		trs []*dsl.Traversal
	)
	v.Count()
	trs = append(trs, v)
	return dsl.Join(trs...)
}

// PCUpdateOne is the builder for updating a single PC entity.
type PCUpdateOne struct {
	Config
	fields   []string
	hooks    []Hook
	mutation *PCMutation
}

// NewPCUpdateOne returns a new PCUpdateOne initialized with the given config, hooks, and mutation.
func NewPCUpdateOne(c Config, hooks []Hook, mutation *PCMutation) *PCUpdateOne {
	return &PCUpdateOne{Config: c, hooks: hooks, mutation: mutation}
}

// Mutation returns the PCMutation object of the builder.
func (_u *PCUpdateOne) Mutation() *PCMutation { return _u.mutation }

// Where appends a list predicates to the PCUpdate builder.
func (_u *PCUpdateOne) Where(ps ...predicate.PC) *PCUpdateOne { _u.mutation.Where(ps...); return _u }

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PCUpdateOne) Select(field string, fields ...string) *PCUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PC entity.
func (_u *PCUpdateOne) Save(ctx context.Context) (*PC, error) {
	return WithHooks(ctx, _u.gremlinSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PCUpdateOne) SaveX(ctx context.Context) *PC { return entbuilder.Must(_u.Save(ctx)) }

// Exec executes the query on the entity.
func (_u *PCUpdateOne) Exec(ctx context.Context) error { _, err := _u.Save(ctx); return err }

// ExecX is like Exec, but panics if an error occurs.
func (_u *PCUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PCUpdateOne) gremlinSave(ctx context.Context) (*PC, error) {
	res := &gremlin.Response{}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", Err: errors.New(`ent: missing "PC.id" for update`)}
	}
	query, bindings := _u.gremlin(id).Query()
	if err := _u.Drv.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	if err, ok := isConstantError(res); ok {
		return nil, err
	}
	_u.mutation.SetDone()
	_m := &PC{Config: _u.Config}
	if err := _m.FromResponse(res); err != nil {
		return nil, err
	}
	return _m, nil
}

func (_u *PCUpdateOne) gremlin(id string) *dsl.Traversal {
	v := g.V(id)
	var (
		trs []*dsl.Traversal
	)
	if len(_u.fields) > 0 {
		fields := make([]any, 0, len(_u.fields)+1)
		fields = append(fields, true)
		for _, f := range _u.fields {
			fields = append(fields, f)
		}
		v.ValueMap(fields...)
	} else {
		v.ValueMap(true)
	}
	trs = append(trs, v)
	return dsl.Join(trs...)
}
