// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package internal

import (
	// Guardrail: internal model package must remain import-cycle safe and must not import
	// generated root query/client packages (alias direction is root -> internal only).
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/runtime/entbuilder"
)

// User is the model entity for the User schema.

type User struct {
	Config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int32 `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Address holds the value of the "address" field.
	Address      string `json:"address,omitempty"`
	selectValues sql.SelectValues
}

// ScanValues returns the types for scanning values from sql.Rows.
func (*User) ScanValues(columns []string) ([]any, error) {
	return entbuilder.ScanTargets(userDescriptor, columns)
}

// AssignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) AssignValues(columns []string, values []any) error {
	return entbuilder.AssignRow(userDescriptor, _m, columns, values, func(c string, v any) {
		_m.selectValues.Set(c, v)
	})
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	unwrapper, ok := _m.Config.Drv.(DriverUnwrapper)
	if !ok {
		panic("internal: User is not a transactional entity")
	}
	_m.Config.Drv = unwrapper.UnwrapDriver()
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	return entbuilder.FormatEntity(userDescriptor, _m)
}

// Users is a parsable slice of User.
type Users []*User
