// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package rental

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/edgefield/ent/predicate"
	"entgo.io/ent/runtime/entfield"
	"github.com/google/uuid"
)

// F holds typed predicate/order handles for every comparable field of the Rental type.
var F = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// Date is the handle for the "date" field.
	Date entfield.Time
	// UserID is the handle for the "user_id" field (backs the "user" edge).
	UserID entfield.EdgeField[int]
	// CarID is the handle for the "car_id" field (backs the "car" edge).
	CarID entfield.EdgeField[uuid.UUID]
}{
	ID:     entfield.NewNumber[int](FieldID, "id"),
	Date:   entfield.NewTime(FieldDate, "date"),
	UserID: entfield.NewEdgeField[int](FieldUserID, "user"),
	CarID:  entfield.NewEdgeField[uuid.UUID](FieldCarID, "car"),
}

// E holds typed edge handles for every edge of the Rental type.
var E = struct {
	// User is the handle for the "user" edge.
	User entfield.Edge[predicate.User, int]
	// Car is the handle for the "car" edge.
	Car entfield.Edge[predicate.Car, uuid.UUID]
}{
	User: entfield.NewEdge[predicate.User, int]("user", newUserStep),
	Car:  entfield.NewEdge[predicate.Car, uuid.UUID]("car", newCarStep),
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.NotPredicates(p))
}
