// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/entc/integration/customid/ent/blob"
	"entgo.io/ent/entc/integration/customid/ent/bloblink"
	"github.com/google/uuid"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	BlobLinkClient     = bloblink.BlobLinkClient
	BlobLinkQuery      = bloblink.BlobLinkQuery
	BlobLinkMutation   = bloblink.BlobLinkMutation
	BlobLinkCreate     = bloblink.BlobLinkCreate
	BlobLinkCreateBulk = bloblink.BlobLinkCreateBulk
	BlobLinkUpdate     = bloblink.BlobLinkUpdate
	BlobLinkUpdateOne  = bloblink.BlobLinkUpdateOne
	BlobLinkDelete     = bloblink.BlobLinkDelete
	BlobLinkDeleteOne  = bloblink.BlobLinkDeleteOne
	BlobLinkGroupBy    = bloblink.BlobLinkGroupBy
	BlobLinkSelect     = bloblink.BlobLinkSelect
	BlobLinkFilter     = bloblink.BlobLinkFilter
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewBlobLinkClient            = bloblink.NewBlobLinkClient
	NewBlobLinkFilterForMutation = bloblink.NewBlobLinkFilterForMutation
)

// WithBlobLinkBlob eager-loads the "blob" edge on a BlobLinkQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithBlobLinkBlob(q *BlobLinkQuery, opts ...func(*BlobQuery)) *BlobLinkQuery {
	sub := NewBlobClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("blob", func(ctx context.Context, parents []*BlobLink) error {
		return loadBlobLinkBlob(ctx, sub, parents)
	})
}

// QueryBlobLinkBlob returns a BlobQuery for the "blob" edge of a given BlobLink.
func QueryBlobLinkBlob(c *BlobLinkClient, _m *BlobLink) *BlobQuery {
	query := NewBlobClient(c.Config).Query()
	return query
}

// loadBlobLinkBlob performs the eager-load for the "blob" edge. Body mirrors
// the pre-PR6 *BlobLinkQuery.loadBlob method, hoisted to root
// so it can reference cross-package types directly.
func loadBlobLinkBlob(ctx context.Context, query *BlobQuery, nodes []*BlobLink) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlobLink)
	for i := range nodes {
		fk := nodes[i].BlobID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blob.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blob_id" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.Blob = n
		}
	}
	return nil
}

// WithBlobLinkLink eager-loads the "link" edge on a BlobLinkQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithBlobLinkLink(q *BlobLinkQuery, opts ...func(*BlobQuery)) *BlobLinkQuery {
	sub := NewBlobClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("link", func(ctx context.Context, parents []*BlobLink) error {
		return loadBlobLinkLink(ctx, sub, parents)
	})
}

// QueryBlobLinkLink returns a BlobQuery for the "link" edge of a given BlobLink.
func QueryBlobLinkLink(c *BlobLinkClient, _m *BlobLink) *BlobQuery {
	query := NewBlobClient(c.Config).Query()
	return query
}

// loadBlobLinkLink performs the eager-load for the "link" edge. Body mirrors
// the pre-PR6 *BlobLinkQuery.loadLink method, hoisted to root
// so it can reference cross-package types directly.
func loadBlobLinkLink(ctx context.Context, query *BlobQuery, nodes []*BlobLink) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlobLink)
	for i := range nodes {
		fk := nodes[i].LinkID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blob.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "link_id" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.Link = n
		}
	}
	return nil
}
