// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/customid/ent/intsid"
	"entgo.io/ent/entc/integration/customid/ent/predicate"
	"entgo.io/ent/entc/integration/customid/sid"
)

// IntSIDClient is a client for the IntSID schema.
type IntSIDClient struct {
	Config
}

// NewIntSIDClient returns a client for the IntSID from the given config.
func NewIntSIDClient(c Config) *IntSIDClient {
	return &IntSIDClient{Config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `intsid.Hooks(f(g(h())))`.
func (c *IntSIDClient) Use(hooks ...Hook) {
	c.Config.Hooks.IntSID = append(c.Config.Hooks.IntSID, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `intsid.Intercept(f(g(h())))`.
func (c *IntSIDClient) Intercept(interceptors ...Interceptor) {
	c.Config.Inters.IntSID = append(c.Config.Inters.IntSID, interceptors...)
}

// Create returns a builder for creating a IntSID entity.
func (c *IntSIDClient) Create() *intsid.IntSIDCreate {
	mutation := NewIntSIDMutation(c.Config, OpCreate)
	return intsid.NewIntSIDCreate(c.Config, c.Hooks(), mutation)
}

// CreateBulk returns a builder for creating a bulk of IntSID entities.
func (c *IntSIDClient) CreateBulk(builders ...*intsid.IntSIDCreate) *intsid.IntSIDCreateBulk {
	return intsid.NewIntSIDCreateBulk(c.Config, builders)
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IntSIDClient) MapCreateBulk(slice any, setFunc func(*intsid.IntSIDCreate, int)) *intsid.IntSIDCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return intsid.NewIntSIDCreateBulkErr(fmt.Errorf("calling to IntSIDClient.MapCreateBulk with wrong type %T, need slice", slice))
	}
	builders := make([]*intsid.IntSIDCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return intsid.NewIntSIDCreateBulk(c.Config, builders)
}

// Update returns an update builder for IntSID.
func (c *IntSIDClient) Update() *intsid.IntSIDUpdate {
	mutation := NewIntSIDMutation(c.Config, OpUpdate, WithIntSIDIDsFunc(func(ctx context.Context, ps ...predicate.IntSID) ([]sid.ID, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return intsid.NewIntSIDUpdate(c.Config, c.Hooks(), mutation)
}

// UpdateOne returns an update builder for the given entity.
func (c *IntSIDClient) UpdateOne(_m *IntSID) *intsid.IntSIDUpdateOne {
	mutation := NewIntSIDMutation(c.Config, OpUpdateOne, WithIntSID(_m))
	return intsid.NewIntSIDUpdateOne(c.Config, c.Hooks(), mutation)
}

// UpdateOneID returns an update builder for the given id.
func (c *IntSIDClient) UpdateOneID(id sid.ID) *intsid.IntSIDUpdateOne {
	mutation := NewIntSIDMutation(c.Config, OpUpdateOne, WithIntSIDID(id, c.Get))
	return intsid.NewIntSIDUpdateOne(c.Config, c.Hooks(), mutation)
}

// Delete returns a delete builder for IntSID.
func (c *IntSIDClient) Delete() *intsid.IntSIDDelete {
	mutation := NewIntSIDMutation(c.Config, OpDelete, WithIntSIDIDsFunc(func(ctx context.Context, ps ...predicate.IntSID) ([]sid.ID, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return intsid.NewIntSIDDelete(c.Config, c.Hooks(), mutation)
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IntSIDClient) DeleteOne(_m *IntSID) *intsid.IntSIDDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IntSIDClient) DeleteOneID(id sid.ID) *intsid.IntSIDDeleteOne {
	mutation := NewIntSIDMutation(c.Config, OpDeleteOne, WithIntSIDID(id, nil))
	mutation.Where(intsid.ID(id))
	return intsid.NewIntSIDDeleteOne(intsid.NewIntSIDDelete(c.Config, c.Hooks(), mutation))
}

// Query returns a query builder for IntSID.
func (c *IntSIDClient) Query() *IntSIDQuery {
	return &IntSIDQuery{
		Config: c.Config,
		ctx:    &QueryContext{Type: TypeIntSID},
		inters: c.Interceptors(),
	}
}

// Get returns a IntSID entity by its id.
func (c *IntSIDClient) Get(ctx context.Context, id sid.ID) (*IntSID, error) {
	return c.Query().Where(intsid.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IntSIDClient) GetX(ctx context.Context, id sid.ID) *IntSID {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a IntSID.
func (c *IntSIDClient) QueryParent(_m *IntSID) *IntSIDQuery {
	query := (&IntSIDClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(intsid.Table, intsid.FieldID, id),
			sqlgraph.To(intsid.Table, intsid.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, intsid.ParentTable, intsid.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a IntSID.
func (c *IntSIDClient) QueryChildren(_m *IntSID) *IntSIDQuery {
	query := (&IntSIDClient{Config: c.Config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(intsid.Table, intsid.FieldID, id),
			sqlgraph.To(intsid.Table, intsid.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, intsid.ChildrenTable, intsid.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IntSIDClient) Hooks() []Hook {
	return c.Config.Hooks.IntSID
}

// Interceptors returns the client interceptors.
func (c *IntSIDClient) Interceptors() []Interceptor {
	return c.Config.Inters.IntSID
}

func (c *IntSIDClient) mutate(ctx context.Context, m *IntSIDMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return intsid.NewIntSIDCreate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdate:
		return intsid.NewIntSIDUpdate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdateOne:
		return intsid.NewIntSIDUpdateOne(c.Config, c.Hooks(), m).Save(ctx)
	case OpDelete, OpDeleteOne:
		return intsid.NewIntSIDDelete(c.Config, c.Hooks(), m).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IntSID mutation op: %q", m.Op())
	}
}
