// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/customid/ent/internal"
)

// LinkMutation is an alias for the internal mutation type.
type LinkMutation = internal.LinkMutation

// LinkMutationOption allows management of the mutation configuration using functional options.
type LinkMutationOption = internal.LinkMutationOption

// NewLinkMutation creates new mutation for the Link entity.
var NewLinkMutation = internal.NewLinkMutation

var WithLinkID = internal.WithLinkID
var WithLink = internal.WithLink
var WithLinkIDsFunc = internal.WithLinkIDsFunc
