// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/customid/ent/edges"
	"entgo.io/ent/entc/integration/customid/ent/user"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	UserClient     = user.UserClient
	UserQuery      = user.UserQuery
	UserMutation   = user.UserMutation
	UserCreate     = user.UserCreate
	UserCreateBulk = user.UserCreateBulk
	UserUpdate     = user.UserUpdate
	UserUpdateOne  = user.UserUpdateOne
	UserDelete     = user.UserDelete
	UserDeleteOne  = user.UserDeleteOne
	UserGroupBy    = user.UserGroupBy
	UserSelect     = user.UserSelect
	UserFilter     = user.UserFilter
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewUserClient            = user.NewUserClient
	NewUserFilterForMutation = user.NewUserFilterForMutation
)

// WithUserGroups forwards to edges.WithUserGroups — body hoisted to gen/edges/user.go for build parallelism.
var WithUserGroups = edges.WithUserGroups

// QueryUserGroups forwards to edges.QueryUserGroups.
var QueryUserGroups = edges.QueryUserGroups

// QueryUserGroupsFromQuery forwards to edges.QueryUserGroupsFromQuery.
var QueryUserGroupsFromQuery = edges.QueryUserGroupsFromQuery

// WithUserParent forwards to edges.WithUserParent — body hoisted to gen/edges/user.go for build parallelism.
var WithUserParent = edges.WithUserParent

// QueryUserParent forwards to edges.QueryUserParent.
var QueryUserParent = edges.QueryUserParent

// QueryUserParentFromQuery forwards to edges.QueryUserParentFromQuery.
var QueryUserParentFromQuery = edges.QueryUserParentFromQuery

// WithUserChildren forwards to edges.WithUserChildren — body hoisted to gen/edges/user.go for build parallelism.
var WithUserChildren = edges.WithUserChildren

// QueryUserChildren forwards to edges.QueryUserChildren.
var QueryUserChildren = edges.QueryUserChildren

// QueryUserChildrenFromQuery forwards to edges.QueryUserChildrenFromQuery.
var QueryUserChildrenFromQuery = edges.QueryUserChildrenFromQuery

// WithUserPets forwards to edges.WithUserPets — body hoisted to gen/edges/user.go for build parallelism.
var WithUserPets = edges.WithUserPets

// QueryUserPets forwards to edges.QueryUserPets.
var QueryUserPets = edges.QueryUserPets

// QueryUserPetsFromQuery forwards to edges.QueryUserPetsFromQuery.
var QueryUserPetsFromQuery = edges.QueryUserPetsFromQuery
