// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package file

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// FileCreate is the builder for creating a File entity.
type FileCreate struct {
	Config
	mutation *FileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// NewFileCreate returns a new FileCreate initialized with the given config, hooks, and mutation.
func NewFileCreate(c Config, hooks []Hook, mutation *FileMutation) *FileCreate {
	return &FileCreate{Config: c, hooks: hooks, mutation: mutation}
}

// SetName sets the "name" field.
func (_c *FileCreate) SetName(v string) *FileCreate {
	_ = _c.mutation.SetField("name", v)
	return _c
}

// AddProcessIDs adds the "processes" edge to the Process entity by IDs.
func (_c *FileCreate) AddProcessIDs(ids ...int) *FileCreate {
	_ = _c.mutation.AddEdgeIDs("processes", entbuilder.ToAny(ids)...)
	return _c
}

// Mutation returns the FileMutation object of the builder.
func (_c *FileCreate) Mutation() *FileMutation {
	return _c.mutation
}

// Save creates the File in the database.
func (_c *FileCreate) Save(ctx context.Context) (*File, error) {
	return WithHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileCreate) SaveX(ctx context.Context) *File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileCreate) check() error {
	if _, ok := entbuilder.GetField[string](_c.mutation, "name"); !ok {
		return &ValidationError{Name: "name", Err: errors.New(`ent: missing required field "File.name"`)}
	}
	return nil
}

func (_c *FileCreate) sqlSave(ctx context.Context) (*File, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.Drv, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.SetID(_node.ID)
	_c.mutation.SetDone()
	return _node, nil
}

func (_c *FileCreate) createSpec() (*File, *sqlgraph.CreateSpec) {
	var (
		_node = &File{Config: _c.Config}
		_spec = sqlgraph.NewCreateSpec(Table, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := entbuilder.GetField[string](_c.mutation, "name"); ok {
		_spec.SetField(FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := entbuilder.EdgeIDsAs[int](_c.mutation, "processes"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ProcessesTable,
			Columns: ProcessesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

type (
	// FileUpsert is the "OnConflict" setter; columns are addressed
	// by their field constants (e.g. file.FieldName).
	FileUpsert = entbuilder.Upsert

	// FileUpsertOne is the builder for "upsert"-ing one File node.
	FileUpsertOne = entbuilder.UpsertOne[int]

	// FileUpsertBulk is the builder for "upsert"-ing many File nodes.
	FileUpsertBulk = entbuilder.UpsertBulk[int]
)

var fileUpsertMeta = entbuilder.UpsertMeta{
	Pkg:           "ent",
	Builder:       "FileCreate",
	IDColumn:      FieldID,
	UserDefinedID: false,
	NumericID:     true,
}

func (_c *FileCreate) upsertConfig() entbuilder.UpsertConfig[int] {
	return entbuilder.UpsertConfig[int]{
		Meta:     &fileUpsertMeta,
		Conflict: &_c.conflict,
		Exec:     _c.Exec,
		SaveID: func(ctx context.Context) (int, error) {
			node, err := _c.Save(ctx)
			if err != nil {
				var zero int
				return zero, err
			}
			return node.ID, nil
		},
		Mutations: func() []entbuilder.FieldReader {
			return []entbuilder.FieldReader{_c.mutation}
		},
		Dialect: func() string { return _c.Drv.Dialect() },
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.File.Create().
//		OnConflict(sql.ResolveWithNewValues()).
//		Update(func(u *ent.FileUpsert) {
//			u.Set(file.FieldX, v)
//		}).
//		Exec(ctx)
func (_c *FileCreate) OnConflict(opts ...sql.ConflictOption) *FileUpsertOne {
	_c.conflict = opts
	return entbuilder.NewUpsertOne(_c.upsertConfig())
}

// OnConflictColumns calls `OnConflict` and configures the columns as conflict target.
func (_c *FileCreate) OnConflictColumns(columns ...string) *FileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return entbuilder.NewUpsertOne(_c.upsertConfig())
}

// FileCreateBulk is the builder for creating many File entities in bulk.
type FileCreateBulk struct {
	Config
	err      error
	builders []*FileCreate
	conflict []sql.ConflictOption
}

// NewFileCreateBulk returns a new FileCreateBulk initialized with the given config and builders.
func NewFileCreateBulk(c Config, builders []*FileCreate) *FileCreateBulk {
	return &FileCreateBulk{Config: c, builders: builders}
}

// NewFileCreateBulkErr returns a new FileCreateBulk that returns the given error on Save.
func NewFileCreateBulkErr(err error) *FileCreateBulk {
	return &FileCreateBulk{err: err}
}

// Save creates the File entities in the database.
func (_c *FileCreateBulk) Save(ctx context.Context) ([]*File, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*File, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.Drv, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{Msg: err.Error(), Wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.SetID(nodes[i].ID)
				mutation.SetDone()
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileCreateBulk) SaveX(ctx context.Context) []*File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_c *FileCreateBulk) upsertBulkConfig() entbuilder.UpsertConfig[int] {
	return entbuilder.UpsertConfig[int]{
		Meta:     &fileUpsertMeta,
		Conflict: &_c.conflict,
		Err:      func() error { return _c.err },
		ChildConflict: func() int {
			for i, b := range _c.builders {
				if len(b.conflict) != 0 {
					return i
				}
			}
			return -1
		},
		Exec: _c.Exec,
		Mutations: func() []entbuilder.FieldReader {
			ms := make([]entbuilder.FieldReader, len(_c.builders))
			for i, b := range _c.builders {
				ms[i] = b.mutation
			}
			return ms
		},
		Dialect: func() string { return _c.Drv.Dialect() },
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement (see FileCreate.OnConflict).
func (_c *FileCreateBulk) OnConflict(opts ...sql.ConflictOption) *FileUpsertBulk {
	_c.conflict = opts
	return entbuilder.NewUpsertBulk(_c.upsertBulkConfig())
}

// OnConflictColumns calls `OnConflict` and configures the columns as conflict target.
func (_c *FileCreateBulk) OnConflictColumns(columns ...string) *FileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return entbuilder.NewUpsertBulk(_c.upsertBulkConfig())
}
