// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"reflect"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/runtime/entbuilder"

	"entgo.io/ent/entc/integration/gremlin/ent/predicate"
)

// NodeMutation is an alias for entbuilder.Mutation parameterised by Node.
type NodeMutation = entbuilder.Mutation[Node, string]

// NodeMutationOption is a functional option for NodeMutation.
type NodeMutationOption = func(*NodeMutation)

// nodeDescriptor describes Node's fields and edges
// for the generic mutation runtime.
var nodeDescriptor = &entbuilder.Descriptor{
	Name:   "Node",
	IDType: reflect.TypeFor[string](),
	Fields: map[string]entbuilder.FieldSpec{
		"value": {
			Type:     reflect.TypeFor[int](),
			GoName:   "Value",
			Nillable: true,
			Numeric:  true,
		},
		"updated_at": {
			Type:     reflect.TypeFor[time.Time](),
			GoName:   "UpdatedAt",
			Nillable: true,
		},
	},
	Edges: map[string]entbuilder.EdgeSpec{
		"prev": {
			Cardinality:  entbuilder.O2OUnique,
			Target:       "Node",
			TargetIDType: reflect.TypeFor[string](),
			Inverse:      true,
		},
		"next": {
			Cardinality:  entbuilder.O2OUnique,
			Target:       "Node",
			TargetIDType: reflect.TypeFor[string](),
		},
	}}

// NewNodeMutation creates a new mutation for the Node entity.
func NewNodeMutation(c Config, op Op, opts ...NodeMutationOption) *NodeMutation {
	return entbuilder.NewMutation[Node, string](&c, op, nodeDescriptor, opts...)
}

// WithNodeID sets the ID field and old-value loader of the mutation.
// The getFunc callback fetches the old entity value for OldField support.
// If getFunc is nil, the old-value loader is not set (used by DeleteOneID).
func WithNodeID(id string, getFunc func(context.Context, string) (*Node, error)) NodeMutationOption {
	return func(m *NodeMutation) {
		m.SetID(id)
		if getFunc != nil {
			m.SetOldValueLoader(func(ctx context.Context) (any, error) { return getFunc(ctx, id) })
		}
	}
}

// WithNode sets the old Node of the mutation.
func WithNode(node *Node) NodeMutationOption {
	return func(m *NodeMutation) {
		m.SetID(node.ID)
		m.SetOldValueLoader(func(context.Context) (any, error) { return node, nil })
	}
}

// WithNodeIDsFunc sets the function used to query entity IDs.
func WithNodeIDsFunc(fn func(context.Context, ...predicate.Node) ([]string, error)) NodeMutationOption {
	return func(m *NodeMutation) {
		m.SetIDsFunc(func(ctx context.Context, preds ...func(*sql.Selector)) ([]any, error) {
			ps := make([]predicate.Node, len(preds))
			for i, p := range preds {
				ps[i] = p
			}
			ids, err := fn(ctx, ps...)
			if err != nil {
				return nil, err
			}
			out := make([]any, len(ids))
			for i, id := range ids {
				out[i] = id
			}
			return out, nil
		})
	}
}
