// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package file

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/ent/predicate"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// FileQuery is the builder for querying File entities.
type FileQuery struct {
	Config
	entbuilder.QueryState[predicate.File]
	order        []OrderOption
	eagerLoaders map[string]func(context.Context, []*File) error
	withFKs      bool
	modifiers    []func(*sql.Selector)
}

// StoreEager registers an eager-load callback for the given edge name.
// Exposed for the root facade's With<Entity><Edge> free functions.
func (_q *FileQuery) StoreEager(name string, loader func(context.Context, []*File) error) *FileQuery {
	if _q.eagerLoaders == nil {
		_q.eagerLoaders = make(map[string]func(context.Context, []*File) error)
	}
	_q.eagerLoaders[name] = loader
	return _q
}

// EagerLoaders returns the registered eager-load callbacks (read-only).
// Used by the sub-package's All() (Task 13) and by root facade utilities.
func (_q *FileQuery) EagerLoaders() map[string]func(context.Context, []*File) error {
	return _q.eagerLoaders
}

// Where adds a new predicate for the FileQuery builder.
func (_q *FileQuery) Where(ps ...predicate.File) *FileQuery {
	_q.AddPredicates(ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FileQuery) Limit(limit int) *FileQuery {
	_q.SetLimit(limit)
	return _q
}

// Offset to start from.
func (_q *FileQuery) Offset(offset int) *FileQuery {
	_q.SetOffset(offset)
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FileQuery) Unique(unique bool) *FileQuery {
	_q.SetUnique(unique)
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FileQuery) Order(o ...OrderOption) *FileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first File entity from the query.
// Returns a *NotFoundError when no File was found.
func (_q *FileQuery) First(ctx context.Context) (*File, error) {
	_q.Limit(1)
	return entbuilder.RunFirst[*File, []*File](ctx, _q, _q.Ctx, ent.OpQueryFirst, Label, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*File, error) { return _q.sqlAll(ctx) }, func(label string) error { return &NotFoundError{Label: label} })
}

// FirstX is like First, but panics if an error occurs.
func (_q *FileQuery) FirstX(ctx context.Context) *File {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first File ID from the query.
// Returns a *NotFoundError when no File ID was found.
func (_q *FileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.Ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{Label: Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FileQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single File entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one File entity is found.
// Returns a *NotFoundError when no File entities are found.
func (_q *FileQuery) Only(ctx context.Context) (*File, error) {
	_q.Limit(2)
	return entbuilder.RunOnly[*File, []*File](ctx, _q, _q.Ctx, ent.OpQueryOnly, Label, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*File, error) { return _q.sqlAll(ctx) }, func(label string) error { return &NotFoundError{Label: label} }, func(label string) error { return &NotSingularError{Label: label} })
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FileQuery) OnlyX(ctx context.Context) *File {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only File ID in the query.
// Returns a *NotSingularError when more than one File ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.Ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{Label: Label}
	default:
		err = &NotSingularError{Label: Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FileQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Files.
func (_q *FileQuery) All(ctx context.Context) ([]*File, error) {
	nodes, err := entbuilder.RunAll[[]*File](ctx, _q, _q.Ctx, ent.OpQueryAll, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*File, error) { return _q.sqlAll(ctx) })
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	// Dispatch any registered eager loaders. Callbacks were captured by
	// the root facade's With<Entity><Edge> free functions and receive the
	// parent slice for in-place edge assignment.
	for _, loader := range _q.eagerLoaders {
		if err := loader(ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// AllX is like All, but panics if an error occurs.
func (_q *FileQuery) AllX(ctx context.Context) []*File {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of File IDs.
func (_q *FileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.Ctx.Unique == nil && _q.Path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.Ctx, ent.OpQueryIDs)
	if err = _q.Select(FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FileQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FileQuery) Count(ctx context.Context) (int, error) {
	return entbuilder.RunCount(ctx, _q, _q.Ctx, ent.OpQueryCount, _q.QueryState.Inters, _q.prepareQuery, _q.sqlCount)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.Ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FileQuery) Clone() *FileQuery {
	if _q == nil {
		return nil
	}
	return &FileQuery{
		Config:       _q.Config,
		QueryState:   *_q.QueryState.Clone(),
		order:        append([]OrderOption{}, _q.order...),
		eagerLoaders: cloneEagerLoadersFile(_q.eagerLoaders),
		modifiers:    append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SetID int `json:"set_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.File.Query().
//		GroupBy(FieldSetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FileQuery) GroupBy(field string, fields ...string) *FileGroupBy {
	_q.Ctx.Fields = append([]string{field}, fields...)
	grbuild := &FileGroupBy{build: _q}
	grbuild.Flds = &_q.Ctx.Fields
	grbuild.Label = Label
	grbuild.ScanFn = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SetID int `json:"set_id,omitempty"`
//	}
//
//	client.File.Query().
//		Select(FieldSetID).
//		Scan(ctx, &v)
func (_q *FileQuery) Select(fields ...string) *FileSelect {
	_q.Ctx.Fields = append(_q.Ctx.Fields, fields...)
	sbuild := &FileSelect{FileQuery: _q}
	sbuild.Label = Label
	sbuild.Flds, sbuild.ScanFn = &_q.Ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FileSelect configured with the given aggregations.
func (_q *FileQuery) Aggregate(fns ...AggregateFunc) *FileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.QueryState.Inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.Ctx.Fields {
		if !ValidColumn(f) {
			return &ValidationError{Name: f, Err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.Path != nil {
		prev, err := _q.Path(ctx)
		if err != nil {
			return err
		}
		_q.Sql = prev
	}
	return nil
}

func (_q *FileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*File, error) {
	var (
		nodes       = []*File{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.eagerLoaders["owner"] != nil,
			_q.eagerLoaders["type"] != nil,
			_q.eagerLoaders["field"] != nil,
		}
	)
	if _q.eagerLoaders["owner"] != nil || _q.eagerLoaders["type"] != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*File).ScanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &File{Config: _q.Config}
		nodes = append(nodes, node)
		node.Edges.SetLoadedTypes(loadedTypes)
		return node.AssignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.Drv, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

// Fetch executes the SQL parent query only — no eager loading.
// Exposed for the root facade's edge-loading helpers (Task 17), which
// call Fetch on a sub-query to materialize neighbors during eager dispatch.
func (_q *FileQuery) Fetch(ctx context.Context, hooks ...queryHook) ([]*File, error) {
	return _q.sqlAll(ctx, hooks...)
}

// PrepareQuery is the exported counterpart of prepareQuery — used by
// root facade eager-load helpers that build join predicates and need
// to attach interceptors/hooks before executing the sub-query.
func (_q *FileQuery) PrepareQuery(ctx context.Context) error {
	return _q.prepareQuery(ctx)
}

func (_q *FileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.Ctx.Fields
	if len(_q.Ctx.Fields) > 0 {
		_spec.Unique = _q.Ctx.Unique != nil && *_q.Ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.Drv, _spec)
}

func (_q *FileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	_spec.From = _q.Sql
	if unique := _q.Ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.Path != nil {
		_spec.Unique = true
	}
	if fields := _q.Ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, FieldID)
		for i := range fields {
			if fields[i] != FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.Predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.Ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.Ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.Drv.Dialect())
	t1 := builder.Table(Table)
	columns := _q.Ctx.Fields
	if len(columns) == 0 {
		columns = Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.Sql != nil {
		selector = _q.Sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.Ctx.Unique != nil && *_q.Ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.Predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.Ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.Ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *FileQuery) ForUpdate(opts ...sql.LockOption) *FileQuery {
	if _q.Drv.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *FileQuery) ForShare(opts ...sql.LockOption) *FileQuery {
	if _q.Drv.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *FileQuery) Modify(modifiers ...func(s *sql.Selector)) *FileSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// FileGroupBy is the group-by builder for File entities.
type FileGroupBy struct {
	selector
	build *FileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FileGroupBy) Aggregate(fns ...AggregateFunc) *FileGroupBy {
	_g.Fns = append(_g.Fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.Ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileQuery, *FileGroupBy](ctx, _g.build, _g, _g.build.QueryState.Inters, v)
}

func (_g *FileGroupBy) sqlScan(ctx context.Context, root *FileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.Fns))
	for _, fn := range _g.Fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.Flds)+len(_g.Fns))
		for _, f := range *_g.Flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.Flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.Drv.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FileSelect is the builder for selecting fields of File entities.
type FileSelect struct {
	*FileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FileSelect) Aggregate(fns ...AggregateFunc) *FileSelect {
	_s.Fns = append(_s.Fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.Ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileQuery, *FileSelect](ctx, _s.FileQuery, _s, _s.QueryState.Inters, v)
}

func (_s *FileSelect) sqlScan(ctx context.Context, root *FileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.Fns))
	for _, fn := range _s.Fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.Flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.Drv.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *FileSelect) Modify(modifiers ...func(s *sql.Selector)) *FileSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}

// fileCreateDescriptor holds the metadata and callbacks for constructing a File entity.
var fileCreateDescriptor = &entbuilder.CreateDescriptor[Config, File, *FileMutation]{
	Table:   Table,
	NewNode: func(c Config) *File { return &File{Config: c} },
	ID: &entbuilder.IDDescriptor[Config, File, *FileMutation]{
		Column:      FieldID,
		Type:        field.TypeInt,
		UserDefined: false,
		AssignGenerated: func(n *File, v driver.Value) error {
			id, ok := v.(int64)
			if !ok {
				return fmt.Errorf("unexpected File.ID type: %T", v)
			}
			n.ID = int(id)
			return nil
		},
	},
}

// cloneEagerLoadersFile returns a shallow copy of the eager-loaders map.
// The closures themselves are shared between original and clone.
func cloneEagerLoadersFile(in map[string]func(context.Context, []*File) error) map[string]func(context.Context, []*File) error {
	if in == nil {
		return nil
	}
	out := make(map[string]func(context.Context, []*File) error, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
