// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package internal

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"entgo.io/ent/entc/gen"

	"github.com/stretchr/testify/require"
)

func TestSnapshot_Restore(t *testing.T) {
	t.Log("Running snapshot-restore integration test")
	const testPackage = "../integration/privacy/ent"
	err := addConflicts(testPackage)
	require.NoError(t, err)
	storage, err := gen.NewStorage("sql")
	require.NoError(t, err)
	snap := &Snapshot{
		Path: filepath.Join(testPackage, "internal/schema.go"),
		Config: &gen.Config{
			Storage: storage,
			Target:  testPackage,
			Schema:  filepath.Join(testPackage, "schema"),
			Header: `
			// Copyright 2019-present Facebook Inc. All rights reserved.
			// This source code is licensed under the Apache 2.0 license found
			// in the LICENSE file in the root directory of this source tree.

			// Code generated by ent, DO NOT EDIT.
			`,
		}}
	require.NoError(t, snap.Restore())
	integrationDir := filepath.Dir(filepath.Dir(testPackage))
	cmd := exec.Command("go", "generate", "./privacy/ent")
	cmd.Dir = integrationDir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "go generate failed in %s:\n%s", integrationDir, string(out))
}

// addConflicts adds VCS conflicts to the files that match the given patterns.
func addConflicts(dir string) error {
	path := filepath.Join(dir, "internal", "schema.go")
	fi, err := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return err
	}
	if _, err := fi.WriteString("\n" + conflictMarker); err != nil {
		_ = fi.Close()
		return err
	}
	return fi.Close()
}
