// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/migrate/entv2/predicate"
	"entgo.io/ent/runtime/entfield"
)

// Field holds typed predicate/order handles for every comparable field of the User type.
var Field = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// MixedString is the handle for the "mixed_string" field.
	MixedString entfield.String[string]
	// MixedEnum is the handle for the "mixed_enum" field.
	MixedEnum entfield.Enum[MixedEnum]
	// Active is the handle for the "active" field.
	Active entfield.Bool[bool]
	// Age is the handle for the "age" field.
	Age entfield.Number[int]
	// Name is the handle for the "name" field.
	Name entfield.String[string]
	// Description is the handle for the "description" field.
	Description entfield.String[string]
	// Nickname is the handle for the "nickname" field.
	Nickname entfield.String[string]
	// Phone is the handle for the "phone" field.
	Phone entfield.String[string]
	// Buffer is the handle for the "buffer" field.
	Buffer entfield.Bytes[[]byte]
	// Title is the handle for the "title" field.
	Title entfield.String[string]
	// NewName is the handle for the "new_name" field.
	NewName entfield.String[string]
	// NewToken is the handle for the "new_token" field.
	NewToken entfield.String[string]
	// Blob is the handle for the "blob" field.
	Blob entfield.Bytes[[]byte]
	// State is the handle for the "state" field.
	State entfield.Enum[State]
	// Status is the handle for the "status" field.
	Status entfield.Enum[Status]
	// Workplace is the handle for the "workplace" field.
	Workplace entfield.String[string]
	// Roles is the handle for the "roles" field.
	Roles entfield.JSON[[]string]
	// DefaultExpr is the handle for the "default_expr" field.
	DefaultExpr entfield.String[string]
	// DefaultExprs is the handle for the "default_exprs" field.
	DefaultExprs entfield.String[string]
	// CreatedAt is the handle for the "created_at" field.
	CreatedAt entfield.Time
	// DropOptional is the handle for the "drop_optional" field.
	DropOptional entfield.String[string]
}{
	ID:           entfield.NewNumber[int](FieldID, "id"),
	MixedString:  entfield.NewString[string](FieldMixedString, "mixed_string"),
	MixedEnum:    entfield.NewEnum[MixedEnum](FieldMixedEnum, "mixed_enum"),
	Active:       entfield.NewBool[bool](FieldActive, "active"),
	Age:          entfield.NewNumber[int](FieldAge, "age"),
	Name:         entfield.NewString[string](FieldName, "name"),
	Description:  entfield.NewString[string](FieldDescription, "description"),
	Nickname:     entfield.NewString[string](FieldNickname, "nickname"),
	Phone:        entfield.NewString[string](FieldPhone, "phone"),
	Buffer:       entfield.NewBytes[[]byte](FieldBuffer, "buffer"),
	Title:        entfield.NewString[string](FieldTitle, "title"),
	NewName:      entfield.NewString[string](FieldNewName, "new_name"),
	NewToken:     entfield.NewString[string](FieldNewToken, "new_token"),
	Blob:         entfield.NewBytes[[]byte](FieldBlob, "blob"),
	State:        entfield.NewEnum[State](FieldState, "state"),
	Status:       entfield.NewEnum[Status](FieldStatus, "status"),
	Workplace:    entfield.NewString[string](FieldWorkplace, "workplace"),
	Roles:        entfield.NewJSON[[]string]("roles"),
	DefaultExpr:  entfield.NewString[string](FieldDefaultExpr, "default_expr"),
	DefaultExprs: entfield.NewString[string](FieldDefaultExprs, "default_exprs"),
	CreatedAt:    entfield.NewTime(FieldCreatedAt, "created_at"),
	DropOptional: entfield.NewString[string](FieldDropOptional, "drop_optional"),
}

// Edge holds typed edge handles for every edge of the User type.
var Edge = struct {
	// Car is the handle for the "car" edge.
	Car entfield.Edge[predicate.Car, int]
	// Pets is the handle for the "pets" edge.
	Pets entfield.Edge[predicate.Pet, int]
	// Friends is the handle for the "friends" edge.
	Friends entfield.Edge[predicate.User, int]
}{
	Car:     entfield.NewEdge[predicate.Car, int]("car", newCarStep),
	Pets:    entfield.NewEdge[predicate.Pet, int]("pets", newPetsStep),
	Friends: entfield.NewEdge[predicate.User, int]("friends", newFriendsStep),
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
