// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/migrate/entv2/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Deprecated: MixedString — use where.EQ(FieldMixedString, v).
func MixedString(v string) predicate.User { return where.EQ(FieldMixedString, v) }

// Deprecated: Active — use where.EQ(FieldActive, v).
func Active(v bool) predicate.User { return where.EQ(FieldActive, v) }

// Deprecated: Age — use where.EQ(FieldAge, v).
func Age(v int) predicate.User { return where.EQ(FieldAge, v) }

// Deprecated: Name — use where.EQ(FieldName, v).
func Name(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: Description — use where.EQ(FieldDescription, v).
func Description(v string) predicate.User { return where.EQ(FieldDescription, v) }

// Deprecated: Nickname — use where.EQ(FieldNickname, v).
func Nickname(v string) predicate.User { return where.EQ(FieldNickname, v) }

// Deprecated: Phone — use where.EQ(FieldPhone, v).
func Phone(v string) predicate.User { return where.EQ(FieldPhone, v) }

// Deprecated: Buffer — use where.EQ(FieldBuffer, v).
func Buffer(v []byte) predicate.User { return where.EQ(FieldBuffer, v) }

// Deprecated: Title — use where.EQ(FieldTitle, v).
func Title(v string) predicate.User { return where.EQ(FieldTitle, v) }

// Deprecated: NewName — use where.EQ(FieldNewName, v).
func NewName(v string) predicate.User { return where.EQ(FieldNewName, v) }

// Deprecated: NewToken — use where.EQ(FieldNewToken, v).
func NewToken(v string) predicate.User { return where.EQ(FieldNewToken, v) }

// Deprecated: Blob — use where.EQ(FieldBlob, v).
func Blob(v []byte) predicate.User { return where.EQ(FieldBlob, v) }

// Deprecated: Workplace — use where.EQ(FieldWorkplace, v).
func Workplace(v string) predicate.User { return where.EQ(FieldWorkplace, v) }

// Deprecated: DefaultExpr — use where.EQ(FieldDefaultExpr, v).
func DefaultExpr(v string) predicate.User { return where.EQ(FieldDefaultExpr, v) }

// Deprecated: DefaultExprs — use where.EQ(FieldDefaultExprs, v).
func DefaultExprs(v string) predicate.User { return where.EQ(FieldDefaultExprs, v) }

// Deprecated: CreatedAt — use where.EQ(FieldCreatedAt, v).
func CreatedAt(v time.Time) predicate.User { return where.EQ(FieldCreatedAt, v) }

// Deprecated: DropOptional — use where.EQ(FieldDropOptional, v).
func DropOptional(v string) predicate.User { return where.EQ(FieldDropOptional, v) }

// Deprecated: MixedStringEQ — use where.EQ(FieldMixedString, v).
func MixedStringEQ(v string) predicate.User { return where.EQ(FieldMixedString, v) }

// Deprecated: MixedStringNEQ — use where.NEQ(FieldMixedString, v).
func MixedStringNEQ(v string) predicate.User { return where.NEQ(FieldMixedString, v) }

// Deprecated: MixedStringIn — use where.In(FieldMixedString, vs...).
func MixedStringIn(vs ...string) predicate.User { return where.In(FieldMixedString, vs...) }

// Deprecated: MixedStringNotIn — use where.NotIn(FieldMixedString, vs...).
func MixedStringNotIn(vs ...string) predicate.User { return where.NotIn(FieldMixedString, vs...) }

// Deprecated: MixedStringGT — use where.GT(FieldMixedString, v).
func MixedStringGT(v string) predicate.User { return where.GT(FieldMixedString, v) }

// Deprecated: MixedStringGTE — use where.GTE(FieldMixedString, v).
func MixedStringGTE(v string) predicate.User { return where.GTE(FieldMixedString, v) }

// Deprecated: MixedStringLT — use where.LT(FieldMixedString, v).
func MixedStringLT(v string) predicate.User { return where.LT(FieldMixedString, v) }

// Deprecated: MixedStringLTE — use where.LTE(FieldMixedString, v).
func MixedStringLTE(v string) predicate.User { return where.LTE(FieldMixedString, v) }

// Deprecated: MixedStringContains — use where.Contains(FieldMixedString, v).
func MixedStringContains(v string) predicate.User { return where.Contains(FieldMixedString, v) }

// Deprecated: MixedStringHasPrefix — use where.HasPrefix(FieldMixedString, v).
func MixedStringHasPrefix(v string) predicate.User { return where.HasPrefix(FieldMixedString, v) }

// Deprecated: MixedStringHasSuffix — use where.HasSuffix(FieldMixedString, v).
func MixedStringHasSuffix(v string) predicate.User { return where.HasSuffix(FieldMixedString, v) }

// Deprecated: MixedStringEqualFold — use where.EqualFold(FieldMixedString, v).
func MixedStringEqualFold(v string) predicate.User { return where.EqualFold(FieldMixedString, v) }

// Deprecated: MixedStringContainsFold — use where.ContainsFold(FieldMixedString, v).
func MixedStringContainsFold(v string) predicate.User { return where.ContainsFold(FieldMixedString, v) }

// Deprecated: MixedEnumEQ — use where.EQ(FieldMixedEnum, v).
func MixedEnumEQ(v MixedEnum) predicate.User { return where.EQ(FieldMixedEnum, v) }

// Deprecated: MixedEnumNEQ — use where.NEQ(FieldMixedEnum, v).
func MixedEnumNEQ(v MixedEnum) predicate.User { return where.NEQ(FieldMixedEnum, v) }

// Deprecated: MixedEnumIn — use where.In(FieldMixedEnum, vs...).
func MixedEnumIn(vs ...MixedEnum) predicate.User { return where.In(FieldMixedEnum, vs...) }

// Deprecated: MixedEnumNotIn — use where.NotIn(FieldMixedEnum, vs...).
func MixedEnumNotIn(vs ...MixedEnum) predicate.User { return where.NotIn(FieldMixedEnum, vs...) }

// Deprecated: ActiveEQ — use where.EQ(FieldActive, v).
func ActiveEQ(v bool) predicate.User { return where.EQ(FieldActive, v) }

// Deprecated: ActiveNEQ — use where.NEQ(FieldActive, v).
func ActiveNEQ(v bool) predicate.User { return where.NEQ(FieldActive, v) }

// Deprecated: AgeEQ — use where.EQ(FieldAge, v).
func AgeEQ(v int) predicate.User { return where.EQ(FieldAge, v) }

// Deprecated: AgeNEQ — use where.NEQ(FieldAge, v).
func AgeNEQ(v int) predicate.User { return where.NEQ(FieldAge, v) }

// Deprecated: AgeIn — use where.In(FieldAge, vs...).
func AgeIn(vs ...int) predicate.User { return where.In(FieldAge, vs...) }

// Deprecated: AgeNotIn — use where.NotIn(FieldAge, vs...).
func AgeNotIn(vs ...int) predicate.User { return where.NotIn(FieldAge, vs...) }

// Deprecated: AgeGT — use where.GT(FieldAge, v).
func AgeGT(v int) predicate.User { return where.GT(FieldAge, v) }

// Deprecated: AgeGTE — use where.GTE(FieldAge, v).
func AgeGTE(v int) predicate.User { return where.GTE(FieldAge, v) }

// Deprecated: AgeLT — use where.LT(FieldAge, v).
func AgeLT(v int) predicate.User { return where.LT(FieldAge, v) }

// Deprecated: AgeLTE — use where.LTE(FieldAge, v).
func AgeLTE(v int) predicate.User { return where.LTE(FieldAge, v) }

// Deprecated: NameEQ — use where.EQ(FieldName, v).
func NameEQ(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: NameNEQ — use where.NEQ(FieldName, v).
func NameNEQ(v string) predicate.User { return where.NEQ(FieldName, v) }

// Deprecated: NameIn — use where.In(FieldName, vs...).
func NameIn(vs ...string) predicate.User { return where.In(FieldName, vs...) }

// Deprecated: NameNotIn — use where.NotIn(FieldName, vs...).
func NameNotIn(vs ...string) predicate.User { return where.NotIn(FieldName, vs...) }

// Deprecated: NameGT — use where.GT(FieldName, v).
func NameGT(v string) predicate.User { return where.GT(FieldName, v) }

// Deprecated: NameGTE — use where.GTE(FieldName, v).
func NameGTE(v string) predicate.User { return where.GTE(FieldName, v) }

// Deprecated: NameLT — use where.LT(FieldName, v).
func NameLT(v string) predicate.User { return where.LT(FieldName, v) }

// Deprecated: NameLTE — use where.LTE(FieldName, v).
func NameLTE(v string) predicate.User { return where.LTE(FieldName, v) }

// Deprecated: NameContains — use where.Contains(FieldName, v).
func NameContains(v string) predicate.User { return where.Contains(FieldName, v) }

// Deprecated: NameHasPrefix — use where.HasPrefix(FieldName, v).
func NameHasPrefix(v string) predicate.User { return where.HasPrefix(FieldName, v) }

// Deprecated: NameHasSuffix — use where.HasSuffix(FieldName, v).
func NameHasSuffix(v string) predicate.User { return where.HasSuffix(FieldName, v) }

// Deprecated: NameEqualFold — use where.EqualFold(FieldName, v).
func NameEqualFold(v string) predicate.User { return where.EqualFold(FieldName, v) }

// Deprecated: NameContainsFold — use where.ContainsFold(FieldName, v).
func NameContainsFold(v string) predicate.User { return where.ContainsFold(FieldName, v) }

// Deprecated: DescriptionEQ — use where.EQ(FieldDescription, v).
func DescriptionEQ(v string) predicate.User { return where.EQ(FieldDescription, v) }

// Deprecated: DescriptionNEQ — use where.NEQ(FieldDescription, v).
func DescriptionNEQ(v string) predicate.User { return where.NEQ(FieldDescription, v) }

// Deprecated: DescriptionIn — use where.In(FieldDescription, vs...).
func DescriptionIn(vs ...string) predicate.User { return where.In(FieldDescription, vs...) }

// Deprecated: DescriptionNotIn — use where.NotIn(FieldDescription, vs...).
func DescriptionNotIn(vs ...string) predicate.User { return where.NotIn(FieldDescription, vs...) }

// Deprecated: DescriptionGT — use where.GT(FieldDescription, v).
func DescriptionGT(v string) predicate.User { return where.GT(FieldDescription, v) }

// Deprecated: DescriptionGTE — use where.GTE(FieldDescription, v).
func DescriptionGTE(v string) predicate.User { return where.GTE(FieldDescription, v) }

// Deprecated: DescriptionLT — use where.LT(FieldDescription, v).
func DescriptionLT(v string) predicate.User { return where.LT(FieldDescription, v) }

// Deprecated: DescriptionLTE — use where.LTE(FieldDescription, v).
func DescriptionLTE(v string) predicate.User { return where.LTE(FieldDescription, v) }

// Deprecated: DescriptionContains — use where.Contains(FieldDescription, v).
func DescriptionContains(v string) predicate.User { return where.Contains(FieldDescription, v) }

// Deprecated: DescriptionHasPrefix — use where.HasPrefix(FieldDescription, v).
func DescriptionHasPrefix(v string) predicate.User { return where.HasPrefix(FieldDescription, v) }

// Deprecated: DescriptionHasSuffix — use where.HasSuffix(FieldDescription, v).
func DescriptionHasSuffix(v string) predicate.User { return where.HasSuffix(FieldDescription, v) }

// Deprecated: DescriptionIsNil — use where.IsNull(FieldDescription).
func DescriptionIsNil() predicate.User { return where.IsNull(FieldDescription) }

// Deprecated: DescriptionNotNil — use where.NotNull(FieldDescription).
func DescriptionNotNil() predicate.User { return where.NotNull(FieldDescription) }

// Deprecated: DescriptionEqualFold — use where.EqualFold(FieldDescription, v).
func DescriptionEqualFold(v string) predicate.User { return where.EqualFold(FieldDescription, v) }

// Deprecated: DescriptionContainsFold — use where.ContainsFold(FieldDescription, v).
func DescriptionContainsFold(v string) predicate.User { return where.ContainsFold(FieldDescription, v) }

// Deprecated: NicknameEQ — use where.EQ(FieldNickname, v).
func NicknameEQ(v string) predicate.User { return where.EQ(FieldNickname, v) }

// Deprecated: NicknameNEQ — use where.NEQ(FieldNickname, v).
func NicknameNEQ(v string) predicate.User { return where.NEQ(FieldNickname, v) }

// Deprecated: NicknameIn — use where.In(FieldNickname, vs...).
func NicknameIn(vs ...string) predicate.User { return where.In(FieldNickname, vs...) }

// Deprecated: NicknameNotIn — use where.NotIn(FieldNickname, vs...).
func NicknameNotIn(vs ...string) predicate.User { return where.NotIn(FieldNickname, vs...) }

// Deprecated: NicknameGT — use where.GT(FieldNickname, v).
func NicknameGT(v string) predicate.User { return where.GT(FieldNickname, v) }

// Deprecated: NicknameGTE — use where.GTE(FieldNickname, v).
func NicknameGTE(v string) predicate.User { return where.GTE(FieldNickname, v) }

// Deprecated: NicknameLT — use where.LT(FieldNickname, v).
func NicknameLT(v string) predicate.User { return where.LT(FieldNickname, v) }

// Deprecated: NicknameLTE — use where.LTE(FieldNickname, v).
func NicknameLTE(v string) predicate.User { return where.LTE(FieldNickname, v) }

// Deprecated: NicknameContains — use where.Contains(FieldNickname, v).
func NicknameContains(v string) predicate.User { return where.Contains(FieldNickname, v) }

// Deprecated: NicknameHasPrefix — use where.HasPrefix(FieldNickname, v).
func NicknameHasPrefix(v string) predicate.User { return where.HasPrefix(FieldNickname, v) }

// Deprecated: NicknameHasSuffix — use where.HasSuffix(FieldNickname, v).
func NicknameHasSuffix(v string) predicate.User { return where.HasSuffix(FieldNickname, v) }

// Deprecated: NicknameEqualFold — use where.EqualFold(FieldNickname, v).
func NicknameEqualFold(v string) predicate.User { return where.EqualFold(FieldNickname, v) }

// Deprecated: NicknameContainsFold — use where.ContainsFold(FieldNickname, v).
func NicknameContainsFold(v string) predicate.User { return where.ContainsFold(FieldNickname, v) }

// Deprecated: PhoneEQ — use where.EQ(FieldPhone, v).
func PhoneEQ(v string) predicate.User { return where.EQ(FieldPhone, v) }

// Deprecated: PhoneNEQ — use where.NEQ(FieldPhone, v).
func PhoneNEQ(v string) predicate.User { return where.NEQ(FieldPhone, v) }

// Deprecated: PhoneIn — use where.In(FieldPhone, vs...).
func PhoneIn(vs ...string) predicate.User { return where.In(FieldPhone, vs...) }

// Deprecated: PhoneNotIn — use where.NotIn(FieldPhone, vs...).
func PhoneNotIn(vs ...string) predicate.User { return where.NotIn(FieldPhone, vs...) }

// Deprecated: PhoneGT — use where.GT(FieldPhone, v).
func PhoneGT(v string) predicate.User { return where.GT(FieldPhone, v) }

// Deprecated: PhoneGTE — use where.GTE(FieldPhone, v).
func PhoneGTE(v string) predicate.User { return where.GTE(FieldPhone, v) }

// Deprecated: PhoneLT — use where.LT(FieldPhone, v).
func PhoneLT(v string) predicate.User { return where.LT(FieldPhone, v) }

// Deprecated: PhoneLTE — use where.LTE(FieldPhone, v).
func PhoneLTE(v string) predicate.User { return where.LTE(FieldPhone, v) }

// Deprecated: PhoneContains — use where.Contains(FieldPhone, v).
func PhoneContains(v string) predicate.User { return where.Contains(FieldPhone, v) }

// Deprecated: PhoneHasPrefix — use where.HasPrefix(FieldPhone, v).
func PhoneHasPrefix(v string) predicate.User { return where.HasPrefix(FieldPhone, v) }

// Deprecated: PhoneHasSuffix — use where.HasSuffix(FieldPhone, v).
func PhoneHasSuffix(v string) predicate.User { return where.HasSuffix(FieldPhone, v) }

// Deprecated: PhoneEqualFold — use where.EqualFold(FieldPhone, v).
func PhoneEqualFold(v string) predicate.User { return where.EqualFold(FieldPhone, v) }

// Deprecated: PhoneContainsFold — use where.ContainsFold(FieldPhone, v).
func PhoneContainsFold(v string) predicate.User { return where.ContainsFold(FieldPhone, v) }

// Deprecated: BufferEQ — use where.EQ(FieldBuffer, v).
func BufferEQ(v []byte) predicate.User { return where.EQ(FieldBuffer, v) }

// Deprecated: BufferNEQ — use where.NEQ(FieldBuffer, v).
func BufferNEQ(v []byte) predicate.User { return where.NEQ(FieldBuffer, v) }

// Deprecated: BufferIn — use where.In(FieldBuffer, vs...).
func BufferIn(vs ...[]byte) predicate.User { return where.In(FieldBuffer, vs...) }

// Deprecated: BufferNotIn — use where.NotIn(FieldBuffer, vs...).
func BufferNotIn(vs ...[]byte) predicate.User { return where.NotIn(FieldBuffer, vs...) }

// Deprecated: BufferGT — use where.GT(FieldBuffer, v).
func BufferGT(v []byte) predicate.User { return where.GT(FieldBuffer, v) }

// Deprecated: BufferGTE — use where.GTE(FieldBuffer, v).
func BufferGTE(v []byte) predicate.User { return where.GTE(FieldBuffer, v) }

// Deprecated: BufferLT — use where.LT(FieldBuffer, v).
func BufferLT(v []byte) predicate.User { return where.LT(FieldBuffer, v) }

// Deprecated: BufferLTE — use where.LTE(FieldBuffer, v).
func BufferLTE(v []byte) predicate.User { return where.LTE(FieldBuffer, v) }

// Deprecated: BufferIsNil — use where.IsNull(FieldBuffer).
func BufferIsNil() predicate.User { return where.IsNull(FieldBuffer) }

// Deprecated: BufferNotNil — use where.NotNull(FieldBuffer).
func BufferNotNil() predicate.User { return where.NotNull(FieldBuffer) }

// Deprecated: TitleEQ — use where.EQ(FieldTitle, v).
func TitleEQ(v string) predicate.User { return where.EQ(FieldTitle, v) }

// Deprecated: TitleNEQ — use where.NEQ(FieldTitle, v).
func TitleNEQ(v string) predicate.User { return where.NEQ(FieldTitle, v) }

// Deprecated: TitleIn — use where.In(FieldTitle, vs...).
func TitleIn(vs ...string) predicate.User { return where.In(FieldTitle, vs...) }

// Deprecated: TitleNotIn — use where.NotIn(FieldTitle, vs...).
func TitleNotIn(vs ...string) predicate.User { return where.NotIn(FieldTitle, vs...) }

// Deprecated: TitleGT — use where.GT(FieldTitle, v).
func TitleGT(v string) predicate.User { return where.GT(FieldTitle, v) }

// Deprecated: TitleGTE — use where.GTE(FieldTitle, v).
func TitleGTE(v string) predicate.User { return where.GTE(FieldTitle, v) }

// Deprecated: TitleLT — use where.LT(FieldTitle, v).
func TitleLT(v string) predicate.User { return where.LT(FieldTitle, v) }

// Deprecated: TitleLTE — use where.LTE(FieldTitle, v).
func TitleLTE(v string) predicate.User { return where.LTE(FieldTitle, v) }

// Deprecated: TitleContains — use where.Contains(FieldTitle, v).
func TitleContains(v string) predicate.User { return where.Contains(FieldTitle, v) }

// Deprecated: TitleHasPrefix — use where.HasPrefix(FieldTitle, v).
func TitleHasPrefix(v string) predicate.User { return where.HasPrefix(FieldTitle, v) }

// Deprecated: TitleHasSuffix — use where.HasSuffix(FieldTitle, v).
func TitleHasSuffix(v string) predicate.User { return where.HasSuffix(FieldTitle, v) }

// Deprecated: TitleEqualFold — use where.EqualFold(FieldTitle, v).
func TitleEqualFold(v string) predicate.User { return where.EqualFold(FieldTitle, v) }

// Deprecated: TitleContainsFold — use where.ContainsFold(FieldTitle, v).
func TitleContainsFold(v string) predicate.User { return where.ContainsFold(FieldTitle, v) }

// Deprecated: NewNameEQ — use where.EQ(FieldNewName, v).
func NewNameEQ(v string) predicate.User { return where.EQ(FieldNewName, v) }

// Deprecated: NewNameNEQ — use where.NEQ(FieldNewName, v).
func NewNameNEQ(v string) predicate.User { return where.NEQ(FieldNewName, v) }

// Deprecated: NewNameIn — use where.In(FieldNewName, vs...).
func NewNameIn(vs ...string) predicate.User { return where.In(FieldNewName, vs...) }

// Deprecated: NewNameNotIn — use where.NotIn(FieldNewName, vs...).
func NewNameNotIn(vs ...string) predicate.User { return where.NotIn(FieldNewName, vs...) }

// Deprecated: NewNameGT — use where.GT(FieldNewName, v).
func NewNameGT(v string) predicate.User { return where.GT(FieldNewName, v) }

// Deprecated: NewNameGTE — use where.GTE(FieldNewName, v).
func NewNameGTE(v string) predicate.User { return where.GTE(FieldNewName, v) }

// Deprecated: NewNameLT — use where.LT(FieldNewName, v).
func NewNameLT(v string) predicate.User { return where.LT(FieldNewName, v) }

// Deprecated: NewNameLTE — use where.LTE(FieldNewName, v).
func NewNameLTE(v string) predicate.User { return where.LTE(FieldNewName, v) }

// Deprecated: NewNameContains — use where.Contains(FieldNewName, v).
func NewNameContains(v string) predicate.User { return where.Contains(FieldNewName, v) }

// Deprecated: NewNameHasPrefix — use where.HasPrefix(FieldNewName, v).
func NewNameHasPrefix(v string) predicate.User { return where.HasPrefix(FieldNewName, v) }

// Deprecated: NewNameHasSuffix — use where.HasSuffix(FieldNewName, v).
func NewNameHasSuffix(v string) predicate.User { return where.HasSuffix(FieldNewName, v) }

// Deprecated: NewNameIsNil — use where.IsNull(FieldNewName).
func NewNameIsNil() predicate.User { return where.IsNull(FieldNewName) }

// Deprecated: NewNameNotNil — use where.NotNull(FieldNewName).
func NewNameNotNil() predicate.User { return where.NotNull(FieldNewName) }

// Deprecated: NewNameEqualFold — use where.EqualFold(FieldNewName, v).
func NewNameEqualFold(v string) predicate.User { return where.EqualFold(FieldNewName, v) }

// Deprecated: NewNameContainsFold — use where.ContainsFold(FieldNewName, v).
func NewNameContainsFold(v string) predicate.User { return where.ContainsFold(FieldNewName, v) }

// Deprecated: NewTokenEQ — use where.EQ(FieldNewToken, v).
func NewTokenEQ(v string) predicate.User { return where.EQ(FieldNewToken, v) }

// Deprecated: NewTokenNEQ — use where.NEQ(FieldNewToken, v).
func NewTokenNEQ(v string) predicate.User { return where.NEQ(FieldNewToken, v) }

// Deprecated: NewTokenIn — use where.In(FieldNewToken, vs...).
func NewTokenIn(vs ...string) predicate.User { return where.In(FieldNewToken, vs...) }

// Deprecated: NewTokenNotIn — use where.NotIn(FieldNewToken, vs...).
func NewTokenNotIn(vs ...string) predicate.User { return where.NotIn(FieldNewToken, vs...) }

// Deprecated: NewTokenGT — use where.GT(FieldNewToken, v).
func NewTokenGT(v string) predicate.User { return where.GT(FieldNewToken, v) }

// Deprecated: NewTokenGTE — use where.GTE(FieldNewToken, v).
func NewTokenGTE(v string) predicate.User { return where.GTE(FieldNewToken, v) }

// Deprecated: NewTokenLT — use where.LT(FieldNewToken, v).
func NewTokenLT(v string) predicate.User { return where.LT(FieldNewToken, v) }

// Deprecated: NewTokenLTE — use where.LTE(FieldNewToken, v).
func NewTokenLTE(v string) predicate.User { return where.LTE(FieldNewToken, v) }

// Deprecated: NewTokenContains — use where.Contains(FieldNewToken, v).
func NewTokenContains(v string) predicate.User { return where.Contains(FieldNewToken, v) }

// Deprecated: NewTokenHasPrefix — use where.HasPrefix(FieldNewToken, v).
func NewTokenHasPrefix(v string) predicate.User { return where.HasPrefix(FieldNewToken, v) }

// Deprecated: NewTokenHasSuffix — use where.HasSuffix(FieldNewToken, v).
func NewTokenHasSuffix(v string) predicate.User { return where.HasSuffix(FieldNewToken, v) }

// Deprecated: NewTokenEqualFold — use where.EqualFold(FieldNewToken, v).
func NewTokenEqualFold(v string) predicate.User { return where.EqualFold(FieldNewToken, v) }

// Deprecated: NewTokenContainsFold — use where.ContainsFold(FieldNewToken, v).
func NewTokenContainsFold(v string) predicate.User { return where.ContainsFold(FieldNewToken, v) }

// Deprecated: BlobEQ — use where.EQ(FieldBlob, v).
func BlobEQ(v []byte) predicate.User { return where.EQ(FieldBlob, v) }

// Deprecated: BlobNEQ — use where.NEQ(FieldBlob, v).
func BlobNEQ(v []byte) predicate.User { return where.NEQ(FieldBlob, v) }

// Deprecated: BlobIn — use where.In(FieldBlob, vs...).
func BlobIn(vs ...[]byte) predicate.User { return where.In(FieldBlob, vs...) }

// Deprecated: BlobNotIn — use where.NotIn(FieldBlob, vs...).
func BlobNotIn(vs ...[]byte) predicate.User { return where.NotIn(FieldBlob, vs...) }

// Deprecated: BlobGT — use where.GT(FieldBlob, v).
func BlobGT(v []byte) predicate.User { return where.GT(FieldBlob, v) }

// Deprecated: BlobGTE — use where.GTE(FieldBlob, v).
func BlobGTE(v []byte) predicate.User { return where.GTE(FieldBlob, v) }

// Deprecated: BlobLT — use where.LT(FieldBlob, v).
func BlobLT(v []byte) predicate.User { return where.LT(FieldBlob, v) }

// Deprecated: BlobLTE — use where.LTE(FieldBlob, v).
func BlobLTE(v []byte) predicate.User { return where.LTE(FieldBlob, v) }

// Deprecated: BlobIsNil — use where.IsNull(FieldBlob).
func BlobIsNil() predicate.User { return where.IsNull(FieldBlob) }

// Deprecated: BlobNotNil — use where.NotNull(FieldBlob).
func BlobNotNil() predicate.User { return where.NotNull(FieldBlob) }

// Deprecated: StateEQ — use where.EQ(FieldState, v).
func StateEQ(v State) predicate.User { return where.EQ(FieldState, v) }

// Deprecated: StateNEQ — use where.NEQ(FieldState, v).
func StateNEQ(v State) predicate.User { return where.NEQ(FieldState, v) }

// Deprecated: StateIn — use where.In(FieldState, vs...).
func StateIn(vs ...State) predicate.User { return where.In(FieldState, vs...) }

// Deprecated: StateNotIn — use where.NotIn(FieldState, vs...).
func StateNotIn(vs ...State) predicate.User { return where.NotIn(FieldState, vs...) }

// Deprecated: StateIsNil — use where.IsNull(FieldState).
func StateIsNil() predicate.User { return where.IsNull(FieldState) }

// Deprecated: StateNotNil — use where.NotNull(FieldState).
func StateNotNil() predicate.User { return where.NotNull(FieldState) }

// Deprecated: StatusEQ — use where.EQ(FieldStatus, v).
func StatusEQ(v Status) predicate.User { return where.EQ(FieldStatus, v) }

// Deprecated: StatusNEQ — use where.NEQ(FieldStatus, v).
func StatusNEQ(v Status) predicate.User { return where.NEQ(FieldStatus, v) }

// Deprecated: StatusIn — use where.In(FieldStatus, vs...).
func StatusIn(vs ...Status) predicate.User { return where.In(FieldStatus, vs...) }

// Deprecated: StatusNotIn — use where.NotIn(FieldStatus, vs...).
func StatusNotIn(vs ...Status) predicate.User { return where.NotIn(FieldStatus, vs...) }

// Deprecated: StatusIsNil — use where.IsNull(FieldStatus).
func StatusIsNil() predicate.User { return where.IsNull(FieldStatus) }

// Deprecated: StatusNotNil — use where.NotNull(FieldStatus).
func StatusNotNil() predicate.User { return where.NotNull(FieldStatus) }

// Deprecated: WorkplaceEQ — use where.EQ(FieldWorkplace, v).
func WorkplaceEQ(v string) predicate.User { return where.EQ(FieldWorkplace, v) }

// Deprecated: WorkplaceNEQ — use where.NEQ(FieldWorkplace, v).
func WorkplaceNEQ(v string) predicate.User { return where.NEQ(FieldWorkplace, v) }

// Deprecated: WorkplaceIn — use where.In(FieldWorkplace, vs...).
func WorkplaceIn(vs ...string) predicate.User { return where.In(FieldWorkplace, vs...) }

// Deprecated: WorkplaceNotIn — use where.NotIn(FieldWorkplace, vs...).
func WorkplaceNotIn(vs ...string) predicate.User { return where.NotIn(FieldWorkplace, vs...) }

// Deprecated: WorkplaceGT — use where.GT(FieldWorkplace, v).
func WorkplaceGT(v string) predicate.User { return where.GT(FieldWorkplace, v) }

// Deprecated: WorkplaceGTE — use where.GTE(FieldWorkplace, v).
func WorkplaceGTE(v string) predicate.User { return where.GTE(FieldWorkplace, v) }

// Deprecated: WorkplaceLT — use where.LT(FieldWorkplace, v).
func WorkplaceLT(v string) predicate.User { return where.LT(FieldWorkplace, v) }

// Deprecated: WorkplaceLTE — use where.LTE(FieldWorkplace, v).
func WorkplaceLTE(v string) predicate.User { return where.LTE(FieldWorkplace, v) }

// Deprecated: WorkplaceContains — use where.Contains(FieldWorkplace, v).
func WorkplaceContains(v string) predicate.User { return where.Contains(FieldWorkplace, v) }

// Deprecated: WorkplaceHasPrefix — use where.HasPrefix(FieldWorkplace, v).
func WorkplaceHasPrefix(v string) predicate.User { return where.HasPrefix(FieldWorkplace, v) }

// Deprecated: WorkplaceHasSuffix — use where.HasSuffix(FieldWorkplace, v).
func WorkplaceHasSuffix(v string) predicate.User { return where.HasSuffix(FieldWorkplace, v) }

// Deprecated: WorkplaceIsNil — use where.IsNull(FieldWorkplace).
func WorkplaceIsNil() predicate.User { return where.IsNull(FieldWorkplace) }

// Deprecated: WorkplaceNotNil — use where.NotNull(FieldWorkplace).
func WorkplaceNotNil() predicate.User { return where.NotNull(FieldWorkplace) }

// Deprecated: WorkplaceEqualFold — use where.EqualFold(FieldWorkplace, v).
func WorkplaceEqualFold(v string) predicate.User { return where.EqualFold(FieldWorkplace, v) }

// Deprecated: WorkplaceContainsFold — use where.ContainsFold(FieldWorkplace, v).
func WorkplaceContainsFold(v string) predicate.User { return where.ContainsFold(FieldWorkplace, v) }

// RolesIsNil applies the IsNil predicate on the "roles" field.
func RolesIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldRoles))
}

// RolesNotNil applies the NotNil predicate on the "roles" field.
func RolesNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldRoles))
}

// Deprecated: DefaultExprEQ — use where.EQ(FieldDefaultExpr, v).
func DefaultExprEQ(v string) predicate.User { return where.EQ(FieldDefaultExpr, v) }

// Deprecated: DefaultExprNEQ — use where.NEQ(FieldDefaultExpr, v).
func DefaultExprNEQ(v string) predicate.User { return where.NEQ(FieldDefaultExpr, v) }

// Deprecated: DefaultExprIn — use where.In(FieldDefaultExpr, vs...).
func DefaultExprIn(vs ...string) predicate.User { return where.In(FieldDefaultExpr, vs...) }

// Deprecated: DefaultExprNotIn — use where.NotIn(FieldDefaultExpr, vs...).
func DefaultExprNotIn(vs ...string) predicate.User { return where.NotIn(FieldDefaultExpr, vs...) }

// Deprecated: DefaultExprGT — use where.GT(FieldDefaultExpr, v).
func DefaultExprGT(v string) predicate.User { return where.GT(FieldDefaultExpr, v) }

// Deprecated: DefaultExprGTE — use where.GTE(FieldDefaultExpr, v).
func DefaultExprGTE(v string) predicate.User { return where.GTE(FieldDefaultExpr, v) }

// Deprecated: DefaultExprLT — use where.LT(FieldDefaultExpr, v).
func DefaultExprLT(v string) predicate.User { return where.LT(FieldDefaultExpr, v) }

// Deprecated: DefaultExprLTE — use where.LTE(FieldDefaultExpr, v).
func DefaultExprLTE(v string) predicate.User { return where.LTE(FieldDefaultExpr, v) }

// Deprecated: DefaultExprContains — use where.Contains(FieldDefaultExpr, v).
func DefaultExprContains(v string) predicate.User { return where.Contains(FieldDefaultExpr, v) }

// Deprecated: DefaultExprHasPrefix — use where.HasPrefix(FieldDefaultExpr, v).
func DefaultExprHasPrefix(v string) predicate.User { return where.HasPrefix(FieldDefaultExpr, v) }

// Deprecated: DefaultExprHasSuffix — use where.HasSuffix(FieldDefaultExpr, v).
func DefaultExprHasSuffix(v string) predicate.User { return where.HasSuffix(FieldDefaultExpr, v) }

// Deprecated: DefaultExprIsNil — use where.IsNull(FieldDefaultExpr).
func DefaultExprIsNil() predicate.User { return where.IsNull(FieldDefaultExpr) }

// Deprecated: DefaultExprNotNil — use where.NotNull(FieldDefaultExpr).
func DefaultExprNotNil() predicate.User { return where.NotNull(FieldDefaultExpr) }

// Deprecated: DefaultExprEqualFold — use where.EqualFold(FieldDefaultExpr, v).
func DefaultExprEqualFold(v string) predicate.User { return where.EqualFold(FieldDefaultExpr, v) }

// Deprecated: DefaultExprContainsFold — use where.ContainsFold(FieldDefaultExpr, v).
func DefaultExprContainsFold(v string) predicate.User { return where.ContainsFold(FieldDefaultExpr, v) }

// Deprecated: DefaultExprsEQ — use where.EQ(FieldDefaultExprs, v).
func DefaultExprsEQ(v string) predicate.User { return where.EQ(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsNEQ — use where.NEQ(FieldDefaultExprs, v).
func DefaultExprsNEQ(v string) predicate.User { return where.NEQ(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsIn — use where.In(FieldDefaultExprs, vs...).
func DefaultExprsIn(vs ...string) predicate.User { return where.In(FieldDefaultExprs, vs...) }

// Deprecated: DefaultExprsNotIn — use where.NotIn(FieldDefaultExprs, vs...).
func DefaultExprsNotIn(vs ...string) predicate.User { return where.NotIn(FieldDefaultExprs, vs...) }

// Deprecated: DefaultExprsGT — use where.GT(FieldDefaultExprs, v).
func DefaultExprsGT(v string) predicate.User { return where.GT(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsGTE — use where.GTE(FieldDefaultExprs, v).
func DefaultExprsGTE(v string) predicate.User { return where.GTE(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsLT — use where.LT(FieldDefaultExprs, v).
func DefaultExprsLT(v string) predicate.User { return where.LT(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsLTE — use where.LTE(FieldDefaultExprs, v).
func DefaultExprsLTE(v string) predicate.User { return where.LTE(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsContains — use where.Contains(FieldDefaultExprs, v).
func DefaultExprsContains(v string) predicate.User { return where.Contains(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsHasPrefix — use where.HasPrefix(FieldDefaultExprs, v).
func DefaultExprsHasPrefix(v string) predicate.User { return where.HasPrefix(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsHasSuffix — use where.HasSuffix(FieldDefaultExprs, v).
func DefaultExprsHasSuffix(v string) predicate.User { return where.HasSuffix(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsIsNil — use where.IsNull(FieldDefaultExprs).
func DefaultExprsIsNil() predicate.User { return where.IsNull(FieldDefaultExprs) }

// Deprecated: DefaultExprsNotNil — use where.NotNull(FieldDefaultExprs).
func DefaultExprsNotNil() predicate.User { return where.NotNull(FieldDefaultExprs) }

// Deprecated: DefaultExprsEqualFold — use where.EqualFold(FieldDefaultExprs, v).
func DefaultExprsEqualFold(v string) predicate.User { return where.EqualFold(FieldDefaultExprs, v) }

// Deprecated: DefaultExprsContainsFold — use where.ContainsFold(FieldDefaultExprs, v).
func DefaultExprsContainsFold(v string) predicate.User {
	return where.ContainsFold(FieldDefaultExprs, v)
}

// Deprecated: CreatedAtEQ — use where.EQ(FieldCreatedAt, v).
func CreatedAtEQ(v time.Time) predicate.User { return where.EQ(FieldCreatedAt, v) }

// Deprecated: CreatedAtNEQ — use where.NEQ(FieldCreatedAt, v).
func CreatedAtNEQ(v time.Time) predicate.User { return where.NEQ(FieldCreatedAt, v) }

// Deprecated: CreatedAtIn — use where.In(FieldCreatedAt, vs...).
func CreatedAtIn(vs ...time.Time) predicate.User { return where.In(FieldCreatedAt, vs...) }

// Deprecated: CreatedAtNotIn — use where.NotIn(FieldCreatedAt, vs...).
func CreatedAtNotIn(vs ...time.Time) predicate.User { return where.NotIn(FieldCreatedAt, vs...) }

// Deprecated: CreatedAtGT — use where.GT(FieldCreatedAt, v).
func CreatedAtGT(v time.Time) predicate.User { return where.GT(FieldCreatedAt, v) }

// Deprecated: CreatedAtGTE — use where.GTE(FieldCreatedAt, v).
func CreatedAtGTE(v time.Time) predicate.User { return where.GTE(FieldCreatedAt, v) }

// Deprecated: CreatedAtLT — use where.LT(FieldCreatedAt, v).
func CreatedAtLT(v time.Time) predicate.User { return where.LT(FieldCreatedAt, v) }

// Deprecated: CreatedAtLTE — use where.LTE(FieldCreatedAt, v).
func CreatedAtLTE(v time.Time) predicate.User { return where.LTE(FieldCreatedAt, v) }

// Deprecated: DropOptionalEQ — use where.EQ(FieldDropOptional, v).
func DropOptionalEQ(v string) predicate.User { return where.EQ(FieldDropOptional, v) }

// Deprecated: DropOptionalNEQ — use where.NEQ(FieldDropOptional, v).
func DropOptionalNEQ(v string) predicate.User { return where.NEQ(FieldDropOptional, v) }

// Deprecated: DropOptionalIn — use where.In(FieldDropOptional, vs...).
func DropOptionalIn(vs ...string) predicate.User { return where.In(FieldDropOptional, vs...) }

// Deprecated: DropOptionalNotIn — use where.NotIn(FieldDropOptional, vs...).
func DropOptionalNotIn(vs ...string) predicate.User { return where.NotIn(FieldDropOptional, vs...) }

// Deprecated: DropOptionalGT — use where.GT(FieldDropOptional, v).
func DropOptionalGT(v string) predicate.User { return where.GT(FieldDropOptional, v) }

// Deprecated: DropOptionalGTE — use where.GTE(FieldDropOptional, v).
func DropOptionalGTE(v string) predicate.User { return where.GTE(FieldDropOptional, v) }

// Deprecated: DropOptionalLT — use where.LT(FieldDropOptional, v).
func DropOptionalLT(v string) predicate.User { return where.LT(FieldDropOptional, v) }

// Deprecated: DropOptionalLTE — use where.LTE(FieldDropOptional, v).
func DropOptionalLTE(v string) predicate.User { return where.LTE(FieldDropOptional, v) }

// Deprecated: DropOptionalContains — use where.Contains(FieldDropOptional, v).
func DropOptionalContains(v string) predicate.User { return where.Contains(FieldDropOptional, v) }

// Deprecated: DropOptionalHasPrefix — use where.HasPrefix(FieldDropOptional, v).
func DropOptionalHasPrefix(v string) predicate.User { return where.HasPrefix(FieldDropOptional, v) }

// Deprecated: DropOptionalHasSuffix — use where.HasSuffix(FieldDropOptional, v).
func DropOptionalHasSuffix(v string) predicate.User { return where.HasSuffix(FieldDropOptional, v) }

// Deprecated: DropOptionalEqualFold — use where.EqualFold(FieldDropOptional, v).
func DropOptionalEqualFold(v string) predicate.User { return where.EqualFold(FieldDropOptional, v) }

// Deprecated: DropOptionalContainsFold — use where.ContainsFold(FieldDropOptional, v).
func DropOptionalContainsFold(v string) predicate.User {
	return where.ContainsFold(FieldDropOptional, v)
}

// HasCar applies the HasEdge predicate on the "car" edge.
func HasCar() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CarTable, CarColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarWith applies the HasEdge predicate on the "car" edge with a given conditions (other predicates).
func HasCarWith(preds ...predicate.Car) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newCarStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasPets applies the HasEdge predicate on the "pets" edge.
func HasPets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PetsTable, PetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetsWith applies the HasEdge predicate on the "pets" edge with a given conditions (other predicates).
func HasPetsWith(preds ...predicate.Pet) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newPetsStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasFriends applies the HasEdge predicate on the "friends" edge.
func HasFriends() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, FriendsTable, FriendsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFriendsWith applies the HasEdge predicate on the "friends" edge with a given conditions (other predicates).
func HasFriendsWith(preds ...predicate.User) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newFriendsStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
