// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package edges

import (
	"context"
	"fmt"

	"entgo.io/ent/entc/integration/edgeschema/ent/group"
	"entgo.io/ent/entc/integration/edgeschema/ent/user"
	"entgo.io/ent/entc/integration/edgeschema/ent/usergroup"
)

// LoadUserGroupUser performs the eager-load for the "user" edge. Body mirrors
// the pre-PR6 *UserGroupQuery.loadUser method, hoisted to root
// so it can reference cross-package types directly.
func LoadUserGroupUser(ctx context.Context, query *user.UserQuery, nodes []*usergroup.UserGroup) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*usergroup.UserGroup)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.User = n
		}
	}
	return nil
}

// LoadUserGroupGroup performs the eager-load for the "group" edge. Body mirrors
// the pre-PR6 *UserGroupQuery.loadGroup method, hoisted to root
// so it can reference cross-package types directly.
func LoadUserGroupGroup(ctx context.Context, query *group.GroupQuery, nodes []*usergroup.UserGroup) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*usergroup.UserGroup)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.Group = n
		}
	}
	return nil
}
