// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/cascadelete/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// Field holds typed predicate/order handles for every comparable field of the User type.
var Field = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// Name is the handle for the "name" field.
	Name entfield.String[string]
}{
	ID:   entfield.NewNumber[int](FieldID, "id"),
	Name: entfield.NewString[string](FieldName, "name"),
}

// Edge holds typed edge handles for every edge of the User type.
var Edge = struct {
	// Posts is the handle for the "posts" edge.
	Posts entfield.Edge[predicate.Post, int]
}{
	Posts: entfield.NewEdge[predicate.Post, int]("posts", newPostsStep),
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
