// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent/entc/integration/multischema/versioned/predicate"
	"entgo.io/ent/runtime/entbuilder"
)

// UserClient is a client for the User schema.
type UserClient struct {
	Config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c Config) *UserClient {
	return &UserClient{Config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.Config.Hooks.User = append(c.Config.Hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.Config.Inters.User = append(c.Config.Inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := NewUserMutation(c.Config, OpCreate)
	return NewUserCreate(c.Config, c.Hooks(), mutation)
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return NewUserCreateBulk(c.Config, builders)
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return NewUserCreateBulkErr(fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice))
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return NewUserCreateBulk(c.Config, builders)
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := NewUserMutation(c.Config, OpUpdate, WithUserIDsFunc(func(ctx context.Context, ps ...predicate.User) ([]int, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return NewUserUpdate(c.Config, c.Hooks(), mutation)
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := NewUserMutation(c.Config, OpUpdateOne, WithUser(_m))
	return NewUserUpdateOne(c.Config, c.Hooks(), mutation)
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := NewUserMutation(c.Config, OpUpdateOne, WithUserID(id, c.Get))
	return NewUserUpdateOne(c.Config, c.Hooks(), mutation)
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := NewUserMutation(c.Config, OpDelete, WithUserIDsFunc(func(ctx context.Context, ps ...predicate.User) ([]int, error) {
		return c.Query().Where(ps...).IDs(ctx)
	}))
	return NewUserDelete(c.Config, c.Hooks(), mutation)
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	mutation := NewUserMutation(c.Config, OpDeleteOne, WithUserID(id, nil))
	mutation.WhereP(ID(id))
	return NewUserDeleteOne(NewUserDelete(c.Config, c.Hooks(), mutation))
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		Config: c.Config,
		QueryState: entbuilder.QueryState[predicate.User]{
			Ctx:    &QueryContext{Type: TypeUser},
			Inters: c.Interceptors(),
		},
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.Config.Hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.Config.Inters.User
}

// Mutate dispatches a mutation to the appropriate builder. Exported so
// the root Client.Mutate switch can dispatch into the sub-package across
// the package boundary (PR 6).
func (c *UserClient) Mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return NewUserCreate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdate:
		return NewUserUpdate(c.Config, c.Hooks(), m).Save(ctx)
	case OpUpdateOne:
		return NewUserUpdateOne(c.Config, c.Hooks(), m).Save(ctx)
	case OpDelete, OpDeleteOne:
		return NewUserDelete(c.Config, c.Hooks(), m).Exec(ctx)
	default:
		return nil, fmt.Errorf("versioned: unknown User mutation op: %q", m.Op())
	}
}
