// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package goods

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// F holds typed predicate/order handles for every comparable field of the Goods type.
var F = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
}{
	ID: entfield.NewNumber[int](FieldID),
}

// E holds typed edge handles for every edge of the Goods type.
var E = struct {
}{}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Goods) predicate.Goods {
	return predicate.Goods(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Goods) predicate.Goods {
	return predicate.Goods(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Goods) predicate.Goods {
	return predicate.Goods(sql.NotPredicates(p))
}
