// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package usertweet

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"
	"entgo.io/ent/runtime/entfield"
)

// F holds typed predicate/order handles for every comparable field of the UserTweet type.
var F = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// CreatedAt is the handle for the "created_at" field.
	CreatedAt entfield.Time
	// UserID is the handle for the "user_id" field.
	UserID entfield.Number[int]
	// TweetID is the handle for the "tweet_id" field.
	TweetID entfield.Number[int]
}{
	ID:        entfield.NewNumber[int](FieldID),
	CreatedAt: entfield.NewTime(FieldCreatedAt),
	UserID:    entfield.NewNumber[int](FieldUserID),
	TweetID:   entfield.NewNumber[int](FieldTweetID),
}

// E holds typed edge handles for every edge of the UserTweet type.
var E = struct {
	// User is the handle for the "user" edge.
	User entfield.Edge[predicate.User]
	// Tweet is the handle for the "tweet" edge.
	Tweet entfield.Edge[predicate.Tweet]
}{
	User:  entfield.NewEdge[predicate.User](newUserStep),
	Tweet: entfield.NewEdge[predicate.Tweet](newTweetStep),
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTweet) predicate.UserTweet {
	return predicate.UserTweet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTweet) predicate.UserTweet {
	return predicate.UserTweet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTweet) predicate.UserTweet {
	return predicate.UserTweet(sql.NotPredicates(p))
}
