// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/edgefield/ent/car"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	CarClient     = car.CarClient
	CarQuery      = car.CarQuery
	CarMutation   = car.CarMutation
	CarCreate     = car.CarCreate
	CarCreateBulk = car.CarCreateBulk
	CarUpdate     = car.CarUpdate
	CarUpdateOne  = car.CarUpdateOne
	CarDelete     = car.CarDelete
	CarDeleteOne  = car.CarDeleteOne
	CarGroupBy    = car.CarGroupBy
	CarSelect     = car.CarSelect
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewCarClient = car.NewCarClient
)
