// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"entgo.io/ent/entc/integration/edgeschema/ent/internal"
)

// Type aliases for types shared between the root package and sub-packages.
type (
	Config           = internal.Config
	Option           = internal.Option
	Hook             = internal.Hook
	Value            = internal.Value
	Query            = internal.Query
	QueryContext     = internal.QueryContext
	Querier          = internal.Querier
	QuerierFunc      = internal.QuerierFunc
	Interceptor      = internal.Interceptor
	InterceptFunc    = internal.InterceptFunc
	Traverser        = internal.Traverser
	TraverseFunc     = internal.TraverseFunc
	Mutator          = internal.Mutator
	Mutation         = internal.Mutation
	MutateFunc       = internal.MutateFunc
	ValidationError  = internal.ValidationError
	NotFoundError    = internal.NotFoundError
	NotSingularError = internal.NotSingularError
	NotLoadedError   = internal.NotLoadedError
	ConstraintError  = internal.ConstraintError
)

const (
	// Operation types.
	OpCreate    = internal.OpCreate
	OpDelete    = internal.OpDelete
	OpDeleteOne = internal.OpDeleteOne
	OpUpdate    = internal.OpUpdate
	OpUpdateOne = internal.OpUpdateOne

	// TypeUser holds the string denoting the user type in the database.
	TypeUser = "User"
)

// WithHooks invokes the builder operation with the given hooks, if any.
func WithHooks[V Value, M any, PM interface {
	*M
	Mutation
}](ctx context.Context, exec func(context.Context) (V, error), mutation PM, hooks []Hook) (value V, err error) {
	return internal.WithHooks[V, M, PM](ctx, exec, mutation, hooks)
}

// Model type aliases from internal.
type User = internal.User
type UserEdges = internal.UserEdges
type Users = internal.Users

// Error-check function aliases for the shared helpers in the internal package.
var (
	IsValidationError = internal.IsValidationError
	IsNotFound        = internal.IsNotFound
	MaskNotFound      = internal.MaskNotFound
	IsNotSingular     = internal.IsNotSingular
	IsNotLoaded       = internal.IsNotLoaded
	IsConstraintError = internal.IsConstraintError
)

// setContextOp is an alias for the shared helper in the internal package.
var setContextOp = internal.SetContextOp

// withInterceptors is a wrapper around internal.WithInterceptors so callers
// can use the conventional lowercase name. Generic functions can't be assigned
// to vars without instantiation, hence the thin wrapper.
func withInterceptors[V Value](ctx context.Context, q Query, qr Querier, inters []Interceptor) (V, error) {
	return internal.WithInterceptors[V](ctx, q, qr, inters)
}

// Type aliases for sql-specific shared helpers.
type (
	selector       = internal.Selector
	AggregateFunc  = internal.AggregateFunc
	queryHook      = internal.QueryHook
	predicateAdder = internal.PredicateAdder
)

// querierAll / querierCount have generic constraints that bind to local
// sqlAll/sqlCount methods (whose identity is package-local because the
// method name is unexported) — so they must be emitted per-sub-package.
func querierAll[V Value, Q interface {
	sqlAll(context.Context, ...queryHook) (V, error)
}]() Querier {
	return QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		return query.sqlAll(ctx)
	})
}

func querierCount[Q interface {
	sqlCount(context.Context) (int, error)
}]() Querier {
	return QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		return query.sqlCount(ctx)
	})
}

// scanWithInterceptors's Q2 constraint references the unexported sqlScan
// method, whose identity is package-local — must stay per-sub-package.
func scanWithInterceptors[Q1 ent.Query, Q2 interface {
	sqlScan(context.Context, Q1, any) error
}](ctx context.Context, rootQuery Q1, selectOrGroup Q2, inters []Interceptor, v any) error {
	rv := reflect.ValueOf(v)
	var qr Querier = QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q1)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		if err := selectOrGroup.sqlScan(ctx, query, v); err != nil {
			return nil, err
		}
		if k := rv.Kind(); k == reflect.Pointer && rv.Elem().CanInterface() {
			return rv.Elem().Interface(), nil
		}
		return v, nil
	})
	for i := len(inters) - 1; i >= 0; i-- {
		qr = inters[i].Intercept(qr)
	}
	vv, err := qr.Query(ctx, rootQuery)
	if err != nil {
		return err
	}
	switch rv2 := reflect.ValueOf(vv); {
	case rv.IsNil(), rv2.IsNil(), rv.Kind() != reflect.Pointer:
	case rv.Type() == rv2.Type():
		rv.Elem().Set(rv2.Elem())
	case rv.Elem().Type() == rv2.Type():
		rv.Elem().Set(rv2)
	}
	return nil
}

// schemaGraph holds this entity's schema for entql predicate evaluation.
// Node 0 is the full self-node; subsequent nodes are stubs for edge targets
// (Type name only — cross-entity field/column metadata is not accessible
// from a leaf sub-package). The stubs are sufficient for entql.HasEdge /
// HasEdgeWith dispatch on the join table; cross-edge field predicates
// against sibling entities are out of scope at the sub-package boundary.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 10)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   Table,
			Columns: Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: FieldID,
			},
		},
		Type: "User",
		Fields: map[string]*sqlgraph.FieldSpec{
			FieldName: {Type: field.TypeString, Column: FieldName},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{Type: "Group"}
	graph.Nodes[2] = &sqlgraph.Node{Type: "Tweet"}
	graph.Nodes[3] = &sqlgraph.Node{Type: "Role"}
	graph.Nodes[4] = &sqlgraph.Node{Type: "UserGroup"}
	graph.Nodes[5] = &sqlgraph.Node{Type: "Friendship"}
	graph.Nodes[6] = &sqlgraph.Node{Type: "Relationship"}
	graph.Nodes[7] = &sqlgraph.Node{Type: "TweetLike"}
	graph.Nodes[8] = &sqlgraph.Node{Type: "UserTweet"}
	graph.Nodes[9] = &sqlgraph.Node{Type: "RoleUser"}
	graph.MustAddE(
		"groups",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   GroupsTable,
			Columns: GroupsPrimaryKey,
			Bidi:    false,
		},
		"User",
		"Group",
	)
	graph.MustAddE(
		"friends",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   FriendsTable,
			Columns: FriendsPrimaryKey,
			Bidi:    true,
		},
		"User",
		"User",
	)
	graph.MustAddE(
		"relatives",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   RelativesTable,
			Columns: RelativesPrimaryKey,
			Bidi:    true,
		},
		"User",
		"User",
	)
	graph.MustAddE(
		"liked_tweets",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   LikedTweetsTable,
			Columns: LikedTweetsPrimaryKey,
			Bidi:    false,
		},
		"User",
		"Tweet",
	)
	graph.MustAddE(
		"tweets",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   TweetsTable,
			Columns: TweetsPrimaryKey,
			Bidi:    false,
		},
		"User",
		"Tweet",
	)
	graph.MustAddE(
		"roles",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   RolesTable,
			Columns: RolesPrimaryKey,
			Bidi:    false,
		},
		"User",
		"Role",
	)
	graph.MustAddE(
		"joined_groups",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   JoinedGroupsTable,
			Columns: []string{JoinedGroupsColumn},
			Bidi:    false,
		},
		"User",
		"UserGroup",
	)
	graph.MustAddE(
		"friendships",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   FriendshipsTable,
			Columns: []string{FriendshipsColumn},
			Bidi:    false,
		},
		"User",
		"Friendship",
	)
	graph.MustAddE(
		"relationship",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   RelationshipTable,
			Columns: []string{RelationshipColumn},
			Bidi:    false,
		},
		"User",
		"Relationship",
	)
	graph.MustAddE(
		"likes",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   LikesTable,
			Columns: []string{LikesColumn},
			Bidi:    false,
		},
		"User",
		"TweetLike",
	)
	graph.MustAddE(
		"user_tweets",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   UserTweetsTable,
			Columns: []string{UserTweetsColumn},
			Bidi:    false,
		},
		"User",
		"UserTweet",
	)
	graph.MustAddE(
		"roles_users",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   RolesUsersTable,
			Columns: []string{RolesUsersColumn},
			Bidi:    false,
		},
		"User",
		"RoleUser",
	)
	return graph
}()
