// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package group

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/ent/predicate"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	Config
	hooks     []Hook
	mutation  *GroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// NewGroupUpdate returns a new GroupUpdate initialized with the given config, hooks, and mutation.
func NewGroupUpdate(c Config, hooks []Hook, mutation *GroupMutation) *GroupUpdate {
	return &GroupUpdate{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate { _u.mutation.Where(ps...); return _u }

// SetActive sets the "active" field.
func (_u *GroupUpdate) SetActive(v bool) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.SetActive, v)
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableActive(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpire sets the "expire" field.
func (_u *GroupUpdate) SetExpire(v time.Time) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.SetExpire, v)
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableExpire(v *time.Time) *GroupUpdate {
	if v != nil {
		_u.SetExpire(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *GroupUpdate) SetType(v string) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.SetType, v)
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableType(v *string) *GroupUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *GroupUpdate) ClearType() *GroupUpdate { return entbuilder.BClear(_u, _u.mutation.ClearType) }

// SetMaxUsers sets the "max_users" field.
func (_u *GroupUpdate) SetMaxUsers(v int) *GroupUpdate {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMaxUsers(v *int) *GroupUpdate {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *GroupUpdate) AddMaxUsers(v int) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.AddMaxUsers, v)
}

// ClearMaxUsers clears the value of the "max_users" field.
func (_u *GroupUpdate) ClearMaxUsers() *GroupUpdate {
	return entbuilder.BClear(_u, _u.mutation.ClearMaxUsers)
}

// SetName sets the "name" field.
func (_u *GroupUpdate) SetName(v string) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.SetName, v)
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableName(v *string) *GroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *GroupUpdate) AddFileIDs(ids ...int) *GroupUpdate { _u.mutation.AddFileIDs(ids...); return _u }

// AddBlockedIDs adds the "blocked" edge to the User entity by IDs.
func (_u *GroupUpdate) AddBlockedIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddBlockedIDs(ids...)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *GroupUpdate) AddUserIDs(ids ...int) *GroupUpdate { _u.mutation.AddUserIDs(ids...); return _u }

// SetInfoID sets the "info" edge to the GroupInfo entity by ID.
func (_u *GroupUpdate) SetInfoID(id int) *GroupUpdate {
	return entbuilder.BSet(_u, _u.mutation.SetInfoID, id)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdate) Mutation() *GroupMutation { return _u.mutation }

// ClearFiles clears all "files" edges to the File entity.
func (_u *GroupUpdate) ClearFiles() *GroupUpdate {
	return entbuilder.BClear(_u, _u.mutation.ClearFiles)
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *GroupUpdate) RemoveFileIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// ClearBlocked clears all "blocked" edges to the User entity.
func (_u *GroupUpdate) ClearBlocked() *GroupUpdate {
	return entbuilder.BClear(_u, _u.mutation.ClearBlocked)
}

// RemoveBlockedIDs removes the "blocked" edge to User entities by IDs.
func (_u *GroupUpdate) RemoveBlockedIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveBlockedIDs(ids...)
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *GroupUpdate) ClearUsers() *GroupUpdate {
	return entbuilder.BClear(_u, _u.mutation.ClearUsers)
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *GroupUpdate) RemoveUserIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// ClearInfo clears the "info" edge to the GroupInfo entity.
func (_u *GroupUpdate) ClearInfo() *GroupUpdate { return entbuilder.BClear(_u, _u.mutation.ClearInfo) }

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUpdate) Save(ctx context.Context) (int, error) {
	return WithHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdate) SaveX(ctx context.Context) int { return entbuilder.Must(_u.Save(ctx)) }

// Exec executes the query.
func (_u *GroupUpdate) Exec(ctx context.Context) error { _, err := _u.Save(ctx); return err }

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", Err: fmt.Errorf(`ent: validator failed for field "Group.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUsers(); ok {
		if err := MaxUsersValidator(v); err != nil {
			return &ValidationError{Name: "max_users", Err: fmt.Errorf(`ent: validator failed for field "Group.max_users": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := NameValidator(v); err != nil {
			return &ValidationError{Name: "name", Err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _u.mutation.InfoCleared() && len(_u.mutation.InfoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.info"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GroupUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GroupUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Expire(); ok {
		_spec.SetField(FieldExpire, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(FieldMaxUsers, field.TypeInt, value)
	}
	if _u.mutation.MaxUsersCleared() {
		_spec.ClearField(FieldMaxUsers, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(FieldName, field.TypeString, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedIDs(); len(nodes) > 0 && !_u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   InfoTable,
			Columns: []string{InfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   InfoTable,
			Columns: []string{InfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return 0, err
	}
	_u.mutation.SetDone()
	return _node, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	Config
	fields    []string
	hooks     []Hook
	mutation  *GroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// NewGroupUpdateOne returns a new GroupUpdateOne initialized with the given config, hooks, and mutation.
func NewGroupUpdateOne(c Config, hooks []Hook, mutation *GroupMutation) *GroupUpdateOne {
	return &GroupUpdateOne{Config: c, hooks: hooks, mutation: mutation}
}

// SetActive sets the "active" field.
func (_u *GroupUpdateOne) SetActive(v bool) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.SetActive, v)
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableActive(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetExpire sets the "expire" field.
func (_u *GroupUpdateOne) SetExpire(v time.Time) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.SetExpire, v)
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableExpire(v *time.Time) *GroupUpdateOne {
	if v != nil {
		_u.SetExpire(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *GroupUpdateOne) SetType(v string) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.SetType, v)
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableType(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *GroupUpdateOne) ClearType() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearType)
}

// SetMaxUsers sets the "max_users" field.
func (_u *GroupUpdateOne) SetMaxUsers(v int) *GroupUpdateOne {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMaxUsers(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *GroupUpdateOne) AddMaxUsers(v int) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.AddMaxUsers, v)
}

// ClearMaxUsers clears the value of the "max_users" field.
func (_u *GroupUpdateOne) ClearMaxUsers() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearMaxUsers)
}

// SetName sets the "name" field.
func (_u *GroupUpdateOne) SetName(v string) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.SetName, v)
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableName(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *GroupUpdateOne) AddFileIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddBlockedIDs adds the "blocked" edge to the User entity by IDs.
func (_u *GroupUpdateOne) AddBlockedIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddBlockedIDs(ids...)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *GroupUpdateOne) AddUserIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// SetInfoID sets the "info" edge to the GroupInfo entity by ID.
func (_u *GroupUpdateOne) SetInfoID(id int) *GroupUpdateOne {
	return entbuilder.BSet(_u, _u.mutation.SetInfoID, id)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdateOne) Mutation() *GroupMutation { return _u.mutation }

// ClearFiles clears all "files" edges to the File entity.
func (_u *GroupUpdateOne) ClearFiles() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearFiles)
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *GroupUpdateOne) RemoveFileIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// ClearBlocked clears all "blocked" edges to the User entity.
func (_u *GroupUpdateOne) ClearBlocked() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearBlocked)
}

// RemoveBlockedIDs removes the "blocked" edge to User entities by IDs.
func (_u *GroupUpdateOne) RemoveBlockedIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveBlockedIDs(ids...)
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *GroupUpdateOne) ClearUsers() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearUsers)
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *GroupUpdateOne) RemoveUserIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// ClearInfo clears the "info" edge to the GroupInfo entity.
func (_u *GroupUpdateOne) ClearInfo() *GroupUpdateOne {
	return entbuilder.BClear(_u, _u.mutation.ClearInfo)
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Group entity.
func (_u *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	return WithHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdateOne) SaveX(ctx context.Context) *Group { return entbuilder.Must(_u.Save(ctx)) }

// Exec executes the query on the entity.
func (_u *GroupUpdateOne) Exec(ctx context.Context) error { _, err := _u.Save(ctx); return err }

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", Err: fmt.Errorf(`ent: validator failed for field "Group.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUsers(); ok {
		if err := MaxUsersValidator(v); err != nil {
			return &ValidationError{Name: "max_users", Err: fmt.Errorf(`ent: validator failed for field "Group.max_users": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := NameValidator(v); err != nil {
			return &ValidationError{Name: "name", Err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _u.mutation.InfoCleared() && len(_u.mutation.InfoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.info"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GroupUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GroupUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", Err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, FieldID)
		for _, f := range fields {
			if !ValidColumn(f) {
				return nil, &ValidationError{Name: f, Err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Expire(); ok {
		_spec.SetField(FieldExpire, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(FieldMaxUsers, field.TypeInt, value)
	}
	if _u.mutation.MaxUsersCleared() {
		_spec.ClearField(FieldMaxUsers, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(FieldName, field.TypeString, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   FilesTable,
			Columns: []string{FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedIDs(); len(nodes) > 0 && !_u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   BlockedTable,
			Columns: []string{BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   UsersTable,
			Columns: UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   InfoTable,
			Columns: []string{InfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   InfoTable,
			Columns: []string{InfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Group{Config: _u.Config}
	_spec.Assign = _node.AssignValues
	_spec.ScanValues = _node.ScanValues
	if err = sqlgraph.UpdateNode(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return nil, err
	}
	_u.mutation.SetDone()
	return _node, nil
}
