// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package node

import (
	"context"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"entgo.io/ent/entc/integration/gremlin/ent/predicate"
)

// NodeDelete is the builder for deleting a Node entity.
type NodeDelete struct {
	Config
	hooks    []Hook
	mutation *NodeMutation
}

// NewNodeDelete returns a new NodeDelete initialized with the given config, hooks, and mutation.
func NewNodeDelete(c Config, hooks []Hook, mutation *NodeMutation) *NodeDelete {
	return &NodeDelete{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the NodeDelete builder.
func (_d *NodeDelete) Where(ps ...predicate.Node) *NodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NodeDelete) Exec(ctx context.Context) (int, error) {
	return WithHooks(ctx, _d.gremlinExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NodeDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := _d.gremlin().Query()
	if err := _d.Drv.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	_d.mutation.SetDone()
	return res.ReadInt()
}

func (_d *NodeDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(Label)
	for _, p := range _d.mutation.MutationPredicates() {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// NodeDeleteOne is the builder for deleting a single Node entity.
type NodeDeleteOne struct {
	_d *NodeDelete
}

// NewNodeDeleteOne returns a new NodeDeleteOne wrapping the given NodeDelete.
func NewNodeDeleteOne(d *NodeDelete) *NodeDeleteOne {
	return &NodeDeleteOne{_d: d}
}

// Where appends a list predicates to the NodeDelete builder.
func (_d *NodeDeleteOne) Where(ps ...predicate.Node) *NodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{Label: Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
