// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package card

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/hooks/ent/predicate"
	"entgo.io/ent/schema/field"
)

// CardDelete is the builder for deleting a Card entity.
type CardDelete struct {
	Config
	hooks    []Hook
	mutation *CardMutation
}

// NewCardDelete returns a new CardDelete initialized with the given config, hooks, and mutation.
func NewCardDelete(c Config, hooks []Hook, mutation *CardMutation) *CardDelete {
	return &CardDelete{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the CardDelete builder.
func (_d *CardDelete) Where(ps ...predicate.Card) *CardDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CardDelete) Exec(ctx context.Context) (int, error) {
	return WithHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(Table, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	if ps := _d.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.Drv, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{Msg: err.Error(), Wrap: err}
	}
	_d.mutation.SetDone()
	return affected, err
}

// CardDeleteOne is the builder for deleting a single Card entity.
type CardDeleteOne struct {
	_d *CardDelete
}

// NewCardDeleteOne returns a new CardDeleteOne wrapping the given CardDelete.
func NewCardDeleteOne(d *CardDelete) *CardDeleteOne {
	return &CardDeleteOne{_d: d}
}

// Where appends a list predicates to the CardDelete builder.
func (_d *CardDeleteOne) Where(ps ...predicate.Card) *CardDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CardDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{Label: Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
