// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package enttask

import (
	"entgo.io/ent/runtime/entbuilder"
)

// TaskDelete is the builder for deleting a Task entity.
type TaskDelete = entbuilder.Delete[Task, int]

// TaskDeleteOne is the builder for deleting a single Task entity.
type TaskDeleteOne = entbuilder.DeleteOne[Task, int]

// NewTaskDelete returns a new TaskDelete initialized with the given config, hooks, and mutation.
func NewTaskDelete(c Config, hooks []Hook, mutation *TaskMutation) *TaskDelete {
	return entbuilder.NewDelete[Task, int](c.Drv, hooks, mutation,
		nil,
		nil,
		func(msg string, wrap error) error { return &ConstraintError{Msg: msg, Wrap: wrap} },
	)
}

// NewTaskDeleteOne returns a new TaskDeleteOne wrapping the given TaskDelete.
func NewTaskDeleteOne(d *TaskDelete) *TaskDeleteOne {
	return entbuilder.NewDeleteOne(d, Label, func(label string) error { return &NotFoundError{Label: label} })
}
