// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package conversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/migrate/entv2/predicate"
	"entgo.io/ent/runtime/entfield"
)

// Field holds typed predicate/order handles for every comparable field of the Conversion type.
var Field = struct {
	// ID is the handle for the id field.
	ID entfield.Number[int]
	// Name is the handle for the "name" field.
	Name entfield.String[string]
	// Int8ToString is the handle for the "int8_to_string" field.
	Int8ToString entfield.String[string]
	// Uint8ToString is the handle for the "uint8_to_string" field.
	Uint8ToString entfield.String[string]
	// Int16ToString is the handle for the "int16_to_string" field.
	Int16ToString entfield.String[string]
	// Uint16ToString is the handle for the "uint16_to_string" field.
	Uint16ToString entfield.String[string]
	// Int32ToString is the handle for the "int32_to_string" field.
	Int32ToString entfield.String[string]
	// Uint32ToString is the handle for the "uint32_to_string" field.
	Uint32ToString entfield.String[string]
	// Int64ToString is the handle for the "int64_to_string" field.
	Int64ToString entfield.String[string]
	// Uint64ToString is the handle for the "uint64_to_string" field.
	Uint64ToString entfield.String[string]
}{
	ID:             entfield.NewNumber[int](FieldID, "id"),
	Name:           entfield.NewString[string](FieldName, "name"),
	Int8ToString:   entfield.NewString[string](FieldInt8ToString, "int8_to_string"),
	Uint8ToString:  entfield.NewString[string](FieldUint8ToString, "uint8_to_string"),
	Int16ToString:  entfield.NewString[string](FieldInt16ToString, "int16_to_string"),
	Uint16ToString: entfield.NewString[string](FieldUint16ToString, "uint16_to_string"),
	Int32ToString:  entfield.NewString[string](FieldInt32ToString, "int32_to_string"),
	Uint32ToString: entfield.NewString[string](FieldUint32ToString, "uint32_to_string"),
	Int64ToString:  entfield.NewString[string](FieldInt64ToString, "int64_to_string"),
	Uint64ToString: entfield.NewString[string](FieldUint64ToString, "uint64_to_string"),
}

// Edge holds typed edge handles for every edge of the Conversion type.
var Edge = struct {
}{}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Conversion) predicate.Conversion {
	return predicate.Conversion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Conversion) predicate.Conversion {
	return predicate.Conversion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Conversion) predicate.Conversion {
	return predicate.Conversion(sql.NotPredicates(p))
}
