// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/idtype/ent/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Deprecated: Name — use where.EQ(FieldName, v).
func Name(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: NameEQ — use where.EQ(FieldName, v).
func NameEQ(v string) predicate.User { return where.EQ(FieldName, v) }

// Deprecated: NameNEQ — use where.NEQ(FieldName, v).
func NameNEQ(v string) predicate.User { return where.NEQ(FieldName, v) }

// Deprecated: NameIn — use where.In(FieldName, vs...).
func NameIn(vs ...string) predicate.User { return where.In(FieldName, vs...) }

// Deprecated: NameNotIn — use where.NotIn(FieldName, vs...).
func NameNotIn(vs ...string) predicate.User { return where.NotIn(FieldName, vs...) }

// Deprecated: NameGT — use where.GT(FieldName, v).
func NameGT(v string) predicate.User { return where.GT(FieldName, v) }

// Deprecated: NameGTE — use where.GTE(FieldName, v).
func NameGTE(v string) predicate.User { return where.GTE(FieldName, v) }

// Deprecated: NameLT — use where.LT(FieldName, v).
func NameLT(v string) predicate.User { return where.LT(FieldName, v) }

// Deprecated: NameLTE — use where.LTE(FieldName, v).
func NameLTE(v string) predicate.User { return where.LTE(FieldName, v) }

// Deprecated: NameContains — use where.Contains(FieldName, v).
func NameContains(v string) predicate.User { return where.Contains(FieldName, v) }

// Deprecated: NameHasPrefix — use where.HasPrefix(FieldName, v).
func NameHasPrefix(v string) predicate.User { return where.HasPrefix(FieldName, v) }

// Deprecated: NameHasSuffix — use where.HasSuffix(FieldName, v).
func NameHasSuffix(v string) predicate.User { return where.HasSuffix(FieldName, v) }

// Deprecated: NameEqualFold — use where.EqualFold(FieldName, v).
func NameEqualFold(v string) predicate.User { return where.EqualFold(FieldName, v) }

// Deprecated: NameContainsFold — use where.ContainsFold(FieldName, v).
func NameContainsFold(v string) predicate.User { return where.ContainsFold(FieldName, v) }

// HasSpouse applies the HasEdge predicate on the "spouse" edge.
func HasSpouse() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SpouseTable, SpouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpouseWith applies the HasEdge predicate on the "spouse" edge with a given conditions (other predicates).
func HasSpouseWith(preds ...predicate.User) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newSpouseStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasFollowers applies the HasEdge predicate on the "followers" edge.
func HasFollowers() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, FollowersTable, FollowersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFollowersWith applies the HasEdge predicate on the "followers" edge with a given conditions (other predicates).
func HasFollowersWith(preds ...predicate.User) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newFollowersStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasFollowing applies the HasEdge predicate on the "following" edge.
func HasFollowing() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, FollowingTable, FollowingPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFollowingWith applies the HasEdge predicate on the "following" edge with a given conditions (other predicates).
func HasFollowingWith(preds ...predicate.User) predicate.User {
	return predicate.User(
		func(s *sql.Selector) {
			step := newFollowingStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
