// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package metadata

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgefield/ent/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Metadata {
	return predicate.Metadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Metadata {
	return predicate.Metadata(sql.FieldLTE(FieldID, id))
}

// Deprecated: Age — use where.EQ(FieldAge, v).
func Age(v int) predicate.Metadata { return where.EQ(FieldAge, v) }

// Deprecated: ParentID — use where.EQ(FieldParentID, v).
func ParentID(v int) predicate.Metadata { return where.EQ(FieldParentID, v) }

// Deprecated: AgeEQ — use where.EQ(FieldAge, v).
func AgeEQ(v int) predicate.Metadata { return where.EQ(FieldAge, v) }

// Deprecated: AgeNEQ — use where.NEQ(FieldAge, v).
func AgeNEQ(v int) predicate.Metadata { return where.NEQ(FieldAge, v) }

// Deprecated: AgeIn — use where.In(FieldAge, vs...).
func AgeIn(vs ...int) predicate.Metadata { return where.In(FieldAge, vs...) }

// Deprecated: AgeNotIn — use where.NotIn(FieldAge, vs...).
func AgeNotIn(vs ...int) predicate.Metadata { return where.NotIn(FieldAge, vs...) }

// Deprecated: AgeGT — use where.GT(FieldAge, v).
func AgeGT(v int) predicate.Metadata { return where.GT(FieldAge, v) }

// Deprecated: AgeGTE — use where.GTE(FieldAge, v).
func AgeGTE(v int) predicate.Metadata { return where.GTE(FieldAge, v) }

// Deprecated: AgeLT — use where.LT(FieldAge, v).
func AgeLT(v int) predicate.Metadata { return where.LT(FieldAge, v) }

// Deprecated: AgeLTE — use where.LTE(FieldAge, v).
func AgeLTE(v int) predicate.Metadata { return where.LTE(FieldAge, v) }

// Deprecated: ParentIDEQ — use where.EQ(FieldParentID, v).
func ParentIDEQ(v int) predicate.Metadata { return where.EQ(FieldParentID, v) }

// Deprecated: ParentIDNEQ — use where.NEQ(FieldParentID, v).
func ParentIDNEQ(v int) predicate.Metadata { return where.NEQ(FieldParentID, v) }

// Deprecated: ParentIDIn — use where.In(FieldParentID, vs...).
func ParentIDIn(vs ...int) predicate.Metadata { return where.In(FieldParentID, vs...) }

// Deprecated: ParentIDNotIn — use where.NotIn(FieldParentID, vs...).
func ParentIDNotIn(vs ...int) predicate.Metadata { return where.NotIn(FieldParentID, vs...) }

// Deprecated: ParentIDIsNil — use where.IsNull(FieldParentID).
func ParentIDIsNil() predicate.Metadata { return where.IsNull(FieldParentID) }

// Deprecated: ParentIDNotNil — use where.NotNull(FieldParentID).
func ParentIDNotNil() predicate.Metadata { return where.NotNull(FieldParentID) }

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Metadata {
	return predicate.Metadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Metadata {
	return predicate.Metadata(
		func(s *sql.Selector) {
			step := newUserStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Metadata {
	return predicate.Metadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(
		func(s *sql.Selector) {
			step := newChildrenStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.Metadata {
	return predicate.Metadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(
		func(s *sql.Selector) {
			step := newParentStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Metadata) predicate.Metadata {
	return predicate.Metadata(sql.NotPredicates(p))
}
