// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Package where provides generic predicate constructors for ent-generated
// query builders. Use it to write field predicates without going through the
// per-entity packages:
//
//	import "entgo.io/ent/where"
//	import "myapp/ent/user"
//
//	client.User.Query().Where(where.EQ(user.FieldName, "alice")).All(ctx)
//
// Each function returns a value assignable to any predicate.<Entity> type
// generated by ent (those types are aliases for func(*sql.Selector)). Compose
// with predicate.User, predicate.Order, etc. interchangeably.
//
// For per-entity legacy wrappers (e.g. user.NameEQ), see the generated
// <entity>/where.go — they remain available as deprecated thin delegates for
// migration purposes.
package where
