// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/multischema/ent/internal"
)

type (
	// Config is the configuration for the client and its builder.
	Config = internal.Config
	// Option function to configure the client.
	Option = internal.Option
)

var (
	// NewConfig creates a new Config for the client.
	NewConfig = internal.NewConfig
	// Debug enables debug logging on the ent.Driver.
	Debug = internal.Debug
	// Log sets the logging function for debug mode.
	Log = internal.Log
	// Driver configures the client driver.
	Driver = internal.Driver
)

var (
	// DefaultSchemaConfig represents the default schema names for all tables as defined in ent/schema.
	DefaultSchemaConfig = SchemaConfig{
		CleanUser:  tableSchemas[0],
		Friendship: tableSchemas[1],
		Group:      tableSchemas[1],
		GroupUsers: tableSchemas[1],
		Parent:     tableSchemas[0],
		Pet:        tableSchemas[0],
		User:       tableSchemas[0],
	}
	tableSchemas = [...]string{"db1", "db2"}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *Config) {
		c.SetSchemaConfig(schemaConfig)
	}
}

// SchemaConfigFromContext returns a SchemaConfig stored inside a context, or empty if there isn't one.
var SchemaConfigFromContext = internal.SchemaConfigFromContext
