// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/multischema/ent/edges"
	"entgo.io/ent/entc/integration/multischema/ent/user"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	UserClient     = user.UserClient
	UserQuery      = user.UserQuery
	UserMutation   = user.UserMutation
	UserCreate     = user.UserCreate
	UserCreateBulk = user.UserCreateBulk
	UserUpdate     = user.UserUpdate
	UserUpdateOne  = user.UserUpdateOne
	UserDelete     = user.UserDelete
	UserDeleteOne  = user.UserDeleteOne
	UserGroupBy    = user.UserGroupBy
	UserSelect     = user.UserSelect
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewUserClient = user.NewUserClient
)

// WithUserPets forwards to edges.WithUserPets — body hoisted to gen/edges/user.go for build parallelism.
var WithUserPets = edges.WithUserPets

// QueryUserPets forwards to edges.QueryUserPets.
var QueryUserPets = edges.QueryUserPets

// QueryUserPetsFromQuery forwards to edges.QueryUserPetsFromQuery.
var QueryUserPetsFromQuery = edges.QueryUserPetsFromQuery

// WithUserGroups forwards to edges.WithUserGroups — body hoisted to gen/edges/user.go for build parallelism.
var WithUserGroups = edges.WithUserGroups

// QueryUserGroups forwards to edges.QueryUserGroups.
var QueryUserGroups = edges.QueryUserGroups

// QueryUserGroupsFromQuery forwards to edges.QueryUserGroupsFromQuery.
var QueryUserGroupsFromQuery = edges.QueryUserGroupsFromQuery

// WithUserFriends forwards to edges.WithUserFriends — body hoisted to gen/edges/user.go for build parallelism.
var WithUserFriends = edges.WithUserFriends

// QueryUserFriends forwards to edges.QueryUserFriends.
var QueryUserFriends = edges.QueryUserFriends

// QueryUserFriendsFromQuery forwards to edges.QueryUserFriendsFromQuery.
var QueryUserFriendsFromQuery = edges.QueryUserFriendsFromQuery

// WithUserParents forwards to edges.WithUserParents — body hoisted to gen/edges/user.go for build parallelism.
var WithUserParents = edges.WithUserParents

// QueryUserParents forwards to edges.QueryUserParents.
var QueryUserParents = edges.QueryUserParents

// QueryUserParentsFromQuery forwards to edges.QueryUserParentsFromQuery.
var QueryUserParentsFromQuery = edges.QueryUserParentsFromQuery

// WithUserChildren forwards to edges.WithUserChildren — body hoisted to gen/edges/user.go for build parallelism.
var WithUserChildren = edges.WithUserChildren

// QueryUserChildren forwards to edges.QueryUserChildren.
var QueryUserChildren = edges.QueryUserChildren

// QueryUserChildrenFromQuery forwards to edges.QueryUserChildrenFromQuery.
var QueryUserChildrenFromQuery = edges.QueryUserChildrenFromQuery

// WithUserFriendships forwards to edges.WithUserFriendships — body hoisted to gen/edges/user.go for build parallelism.
var WithUserFriendships = edges.WithUserFriendships

// QueryUserFriendships forwards to edges.QueryUserFriendships.
var QueryUserFriendships = edges.QueryUserFriendships

// QueryUserFriendshipsFromQuery forwards to edges.QueryUserFriendshipsFromQuery.
var QueryUserFriendshipsFromQuery = edges.QueryUserFriendshipsFromQuery

// WithUserParentHood forwards to edges.WithUserParentHood — body hoisted to gen/edges/user.go for build parallelism.
var WithUserParentHood = edges.WithUserParentHood

// QueryUserParentHood forwards to edges.QueryUserParentHood.
var QueryUserParentHood = edges.QueryUserParentHood

// QueryUserParentHoodFromQuery forwards to edges.QueryUserParentHoodFromQuery.
var QueryUserParentHoodFromQuery = edges.QueryUserParentHoodFromQuery
