// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package revision

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// RevisionCreate is the builder for creating a Revision entity.
type RevisionCreate struct {
	Config
	mutation *RevisionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// NewRevisionCreate returns a new RevisionCreate initialized with the given config, hooks, and mutation.
func NewRevisionCreate(c Config, hooks []Hook, mutation *RevisionMutation) *RevisionCreate {
	return &RevisionCreate{Config: c, hooks: hooks, mutation: mutation}
}

// SetID sets the "id" field.
func (_c *RevisionCreate) SetID(v string) *RevisionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RevisionMutation object of the builder.
func (_c *RevisionCreate) Mutation() *RevisionMutation {
	return _c.mutation
}

// Save creates the Revision in the database.
func (_c *RevisionCreate) Save(ctx context.Context) (*Revision, error) {
	return WithHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RevisionCreate) SaveX(ctx context.Context) *Revision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RevisionCreate) check() error {
	return nil
}

func (_c *RevisionCreate) sqlSave(ctx context.Context) (*Revision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.Drv, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Revision.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.SetID(_node.ID)
	_c.mutation.SetDone()
	return _node, nil
}

func (_c *RevisionCreate) createSpec() (*Revision, *sqlgraph.CreateSpec) {
	var (
		_node = &Revision{Config: _c.Config}
		_spec = sqlgraph.NewCreateSpec(Table, sqlgraph.NewFieldSpec(FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	return _node, _spec
}

type (
	// RevisionUpsert is the "OnConflict" setter; columns are addressed
	// by their field constants (e.g. revision.FieldName).
	RevisionUpsert = entbuilder.Upsert

	// RevisionUpsertOne is the builder for "upsert"-ing one Revision node.
	RevisionUpsertOne = entbuilder.UpsertOne[string]

	// RevisionUpsertBulk is the builder for "upsert"-ing many Revision nodes.
	RevisionUpsertBulk = entbuilder.UpsertBulk[string]
)

var revisionUpsertMeta = entbuilder.UpsertMeta{
	Pkg:           "ent",
	Builder:       "RevisionCreate",
	IDColumn:      FieldID,
	UserDefinedID: true,
	NumericID:     false,
}

func (_c *RevisionCreate) upsertConfig() entbuilder.UpsertConfig[string] {
	return entbuilder.UpsertConfig[string]{
		Meta:     &revisionUpsertMeta,
		Conflict: &_c.conflict,
		Exec:     _c.Exec,
		SaveID: func(ctx context.Context) (string, error) {
			node, err := _c.Save(ctx)
			if err != nil {
				var zero string
				return zero, err
			}
			return node.ID, nil
		},
		IDsSet: func() []bool {
			_, ok := _c.mutation.ID()
			return []bool{ok}
		},
		Mutations: func() []entbuilder.FieldReader {
			return []entbuilder.FieldReader{_c.mutation}
		},
		Dialect: _c.Drv.Dialect,
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Revision.Create().
//		OnConflict(sql.ResolveWithNewValues()).
//		Update(func(u *ent.RevisionUpsert) {
//			u.Set(revision.FieldX, v)
//		}).
//		Exec(ctx)
func (_c *RevisionCreate) OnConflict(opts ...sql.ConflictOption) *RevisionUpsertOne {
	_c.conflict = opts
	return entbuilder.NewUpsertOne(_c.upsertConfig())
}

// OnConflictColumns calls `OnConflict` and configures the columns as conflict target.
func (_c *RevisionCreate) OnConflictColumns(columns ...string) *RevisionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return entbuilder.NewUpsertOne(_c.upsertConfig())
}

// RevisionCreateBulk is the builder for creating many Revision entities in bulk.
type RevisionCreateBulk struct {
	Config
	err      error
	builders []*RevisionCreate
	conflict []sql.ConflictOption
}

// NewRevisionCreateBulk returns a new RevisionCreateBulk initialized with the given config and builders.
func NewRevisionCreateBulk(c Config, builders []*RevisionCreate) *RevisionCreateBulk {
	return &RevisionCreateBulk{Config: c, builders: builders}
}

// NewRevisionCreateBulkErr returns a new RevisionCreateBulk that returns the given error on Save.
func NewRevisionCreateBulkErr(err error) *RevisionCreateBulk {
	return &RevisionCreateBulk{err: err}
}

// Save creates the Revision entities in the database.
func (_c *RevisionCreateBulk) Save(ctx context.Context) ([]*Revision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Revision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.Drv, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{Msg: err.Error(), Wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.SetID(nodes[i].ID)
				mutation.SetDone()
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RevisionCreateBulk) SaveX(ctx context.Context) []*Revision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_c *RevisionCreateBulk) upsertBulkConfig() entbuilder.UpsertConfig[string] {
	return entbuilder.UpsertConfig[string]{
		Meta:     &revisionUpsertMeta,
		Conflict: &_c.conflict,
		Err:      func() error { return _c.err },
		ChildConflict: func() int {
			for i, b := range _c.builders {
				if len(b.conflict) != 0 {
					return i
				}
			}
			return -1
		},
		Exec: _c.Exec,
		IDsSet: func() []bool {
			set := make([]bool, len(_c.builders))
			for i, b := range _c.builders {
				_, set[i] = b.mutation.ID()
			}
			return set
		},
		Mutations: func() []entbuilder.FieldReader {
			ms := make([]entbuilder.FieldReader, len(_c.builders))
			for i, b := range _c.builders {
				ms[i] = b.mutation
			}
			return ms
		},
		Dialect: _c.Drv.Dialect,
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement (see RevisionCreate.OnConflict).
func (_c *RevisionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RevisionUpsertBulk {
	_c.conflict = opts
	return entbuilder.NewUpsertBulk(_c.upsertBulkConfig())
}

// OnConflictColumns calls `OnConflict` and configures the columns as conflict target.
func (_c *RevisionCreateBulk) OnConflictColumns(columns ...string) *RevisionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return entbuilder.NewUpsertBulk(_c.upsertBulkConfig())
}
