// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/entc/integration/gremlin/ent/internal"
)

// FileMutation is an alias for the internal mutation type.
type FileMutation = internal.FileMutation

// FileMutationOption allows management of the mutation configuration using functional options.
type FileMutationOption = internal.FileMutationOption

// NewFileMutation creates new mutation for the File entity.
var NewFileMutation = internal.NewFileMutation

var WithFileID = internal.WithFileID
var WithFile = internal.WithFile
var WithFileIDsFunc = internal.WithFileIDsFunc
