// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package grouptag

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"
	"entgo.io/ent/where"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GroupTag {
	return predicate.GroupTag(sql.FieldLTE(FieldID, id))
}

// Deprecated: TagID — use where.EQ(FieldTagID, v).
func TagID(v int) predicate.GroupTag { return where.EQ(FieldTagID, v) }

// Deprecated: GroupID — use where.EQ(FieldGroupID, v).
func GroupID(v int) predicate.GroupTag { return where.EQ(FieldGroupID, v) }

// Deprecated: TagIDEQ — use where.EQ(FieldTagID, v).
func TagIDEQ(v int) predicate.GroupTag { return where.EQ(FieldTagID, v) }

// Deprecated: TagIDNEQ — use where.NEQ(FieldTagID, v).
func TagIDNEQ(v int) predicate.GroupTag { return where.NEQ(FieldTagID, v) }

// Deprecated: TagIDIn — use where.In(FieldTagID, vs...).
func TagIDIn(vs ...int) predicate.GroupTag { return where.In(FieldTagID, vs...) }

// Deprecated: TagIDNotIn — use where.NotIn(FieldTagID, vs...).
func TagIDNotIn(vs ...int) predicate.GroupTag { return where.NotIn(FieldTagID, vs...) }

// Deprecated: GroupIDEQ — use where.EQ(FieldGroupID, v).
func GroupIDEQ(v int) predicate.GroupTag { return where.EQ(FieldGroupID, v) }

// Deprecated: GroupIDNEQ — use where.NEQ(FieldGroupID, v).
func GroupIDNEQ(v int) predicate.GroupTag { return where.NEQ(FieldGroupID, v) }

// Deprecated: GroupIDIn — use where.In(FieldGroupID, vs...).
func GroupIDIn(vs ...int) predicate.GroupTag { return where.In(FieldGroupID, vs...) }

// Deprecated: GroupIDNotIn — use where.NotIn(FieldGroupID, vs...).
func GroupIDNotIn(vs ...int) predicate.GroupTag { return where.NotIn(FieldGroupID, vs...) }

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.GroupTag {
	return predicate.GroupTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TagTable, TagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.GroupTag {
	return predicate.GroupTag(
		func(s *sql.Selector) {
			step := newTagStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupTag {
	return predicate.GroupTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupTag {
	return predicate.GroupTag(
		func(s *sql.Selector) {
			step := newGroupStep()
			sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
				for _, p := range preds {
					p(s)
				}
			})
		})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupTag) predicate.GroupTag {
	return predicate.GroupTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupTag) predicate.GroupTag {
	return predicate.GroupTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupTag) predicate.GroupTag {
	return predicate.GroupTag(sql.NotPredicates(p))
}
